
module.snapshot.git.hash=6763723ca1571be5fc05e435171d6c1c08c840bf
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.portal.search.lucene/1.0.0-SNAPSHOT/com.liferay.portal.search.lucene-1.0.0-20150528.044744-1.jar
			