
module.snapshot.git.hash=f81d54ecfcb66cb642c0f05fb07b4b7b5da29ea6
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.document.library.repository.cmis/1.0.0-SNAPSHOT/com.liferay.document.library.repository.cmis-1.0.0-20150528.042022-2.jar
			