create index IX_430D791F on BlogsEntry (companyId, displayDate);
create index IX_8CACE77B on BlogsEntry (companyId, userId);
create index IX_7832EBD6 on BlogsEntry (externalReferenceCode[$COLUMN_LENGTH:75$]);
create index IX_621E19D on BlogsEntry (groupId, displayDate);
create unique index IX_38CAA07E on BlogsEntry (groupId, urlTitle[$COLUMN_LENGTH:255$], ctCollectionId);
create index IX_FBDE0AA3 on BlogsEntry (groupId, userId, displayDate);
create index IX_BB0C2905 on BlogsEntry (status, companyId, displayDate);
create index IX_A5F57B61 on BlogsEntry (status, companyId, userId);
create index IX_2672F77F on BlogsEntry (status, displayDate);
create index IX_F0E73383 on BlogsEntry (status, groupId, displayDate);
create index IX_DA04F689 on BlogsEntry (status, groupId, userId, displayDate);
create index IX_69157A4D on BlogsEntry (uuid_[$COLUMN_LENGTH:75$]);