
module.snapshot.git.hash=abce78ad8d412a63347e12fb1176d6b7e3cecb69
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.wiki.service/1.0.0-SNAPSHOT/com.liferay.wiki.service-1.0.0-20150528.042951-2.jar
			