/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.blogs.service.base;

import com.liferay.asset.kernel.service.persistence.AssetEntryPersistence;
import com.liferay.asset.kernel.service.persistence.AssetLinkPersistence;

import com.liferay.blogs.model.BlogsEntry;
import com.liferay.blogs.service.BlogsEntryService;
import com.liferay.blogs.service.persistence.BlogsEntryFinder;
import com.liferay.blogs.service.persistence.BlogsEntryPersistence;
import com.liferay.blogs.service.persistence.BlogsStatsUserFinder;
import com.liferay.blogs.service.persistence.BlogsStatsUserPersistence;

import com.liferay.expando.kernel.service.persistence.ExpandoRowPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.CompanyPersistence;
import com.liferay.portal.kernel.service.persistence.GroupPersistence;
import com.liferay.portal.kernel.service.persistence.ImagePersistence;
import com.liferay.portal.kernel.service.persistence.OrganizationPersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.service.persistence.WorkflowInstanceLinkPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import com.liferay.ratings.kernel.service.persistence.RatingsStatsPersistence;

import org.osgi.service.component.annotations.Reference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the blogs entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.blogs.service.impl.BlogsEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.blogs.service.impl.BlogsEntryServiceImpl
 * @see com.liferay.blogs.service.BlogsEntryServiceUtil
 * @generated
 */
public abstract class BlogsEntryServiceBaseImpl extends BaseServiceImpl
	implements AopService, BlogsEntryService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.blogs.service.BlogsEntryServiceUtil} to access the blogs entry remote service.
	 */

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BlogsEntryService.class.getName();
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class[] {
			BlogsEntryService.class, BaseService.class,
			IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		blogsEntryService = (BlogsEntryService)aopProxy;
	}

	protected Class<?> getModelClass() {
		return BlogsEntry.class;
	}

	protected String getModelClassName() {
		return BlogsEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = blogsEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@Reference
	protected com.liferay.blogs.service.BlogsEntryLocalService blogsEntryLocalService;
	protected BlogsEntryService blogsEntryService;
	@Reference
	protected BlogsEntryPersistence blogsEntryPersistence;
	@Reference
	protected BlogsEntryFinder blogsEntryFinder;
	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.CompanyLocalService companyLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.CompanyService companyService;
	@Reference
	protected CompanyPersistence companyPersistence;
	@Reference
	protected com.liferay.portal.kernel.service.GroupLocalService groupLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.GroupService groupService;
	@Reference
	protected GroupPersistence groupPersistence;
	@Reference
	protected com.liferay.portal.kernel.service.ImageLocalService imageLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.ImageService imageService;
	@Reference
	protected ImagePersistence imagePersistence;
	@Reference
	protected com.liferay.portal.kernel.service.OrganizationLocalService organizationLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.OrganizationService organizationService;
	@Reference
	protected OrganizationPersistence organizationPersistence;
	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;
	@Reference
	protected UserPersistence userPersistence;
	@Reference
	protected com.liferay.portal.kernel.service.WorkflowInstanceLinkLocalService workflowInstanceLinkLocalService;
	@Reference
	protected WorkflowInstanceLinkPersistence workflowInstanceLinkPersistence;
	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService assetEntryLocalService;
	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryService assetEntryService;
	@Reference
	protected AssetEntryPersistence assetEntryPersistence;
	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService assetLinkLocalService;
	@Reference
	protected AssetLinkPersistence assetLinkPersistence;
	@Reference
	protected com.liferay.expando.kernel.service.ExpandoRowLocalService expandoRowLocalService;
	@Reference
	protected ExpandoRowPersistence expandoRowPersistence;
	@Reference
	protected com.liferay.ratings.kernel.service.RatingsStatsLocalService ratingsStatsLocalService;
	@Reference
	protected RatingsStatsPersistence ratingsStatsPersistence;
	@Reference
	protected com.liferay.blogs.service.BlogsStatsUserLocalService blogsStatsUserLocalService;
	@Reference
	protected BlogsStatsUserPersistence blogsStatsUserPersistence;
	@Reference
	protected BlogsStatsUserFinder blogsStatsUserFinder;
}