/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.ABCTestEntityLocalization;
import com.liferay.portal.kernel.model.ABCTestEntityLocalizationModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ABCTestEntityLocalization service. Represents a row in the &quot;ABCTestEntityLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ABCTestEntityLocalizationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ABCTestEntityLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ABCTestEntityLocalizationImpl
 * @see ABCTestEntityLocalization
 * @see ABCTestEntityLocalizationModel
 * @generated
 */
@ProviderType
public class ABCTestEntityLocalizationModelImpl extends BaseModelImpl<ABCTestEntityLocalization>
	implements ABCTestEntityLocalizationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a abc test entity localization model instance should use the {@link ABCTestEntityLocalization} interface instead.
	 */
	public static final String TABLE_NAME = "ABCTestEntityLocalization";
	public static final Object[][] TABLE_COLUMNS = {
			{ "mvccVersion", Types.BIGINT },
			{ "abcTestEntityLocalizationId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "abcTestEntityId", Types.VARCHAR },
			{ "languageId", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "groupId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("abcTestEntityLocalizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("abcTestEntityId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table ABCTestEntityLocalization (mvccVersion LONG default 0 not null,abcTestEntityLocalizationId LONG not null primary key,companyId LONG,abcTestEntityId VARCHAR(75) null,languageId VARCHAR(75) null,name VARCHAR(75) null,description VARCHAR(75) null,groupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ABCTestEntityLocalization";
	public static final String ORDER_BY_JPQL = " ORDER BY ";
	public static final String ORDER_BY_SQL = " ORDER BY ";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portal.kernel.model.ABCTestEntityLocalization"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portal.kernel.model.ABCTestEntityLocalization"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.kernel.model.ABCTestEntityLocalization"),
			true);
	public static final long ABCTESTENTITYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LANGUAGEID_COLUMN_BITMASK = 4L;
	public static final long NAME_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portal.kernel.model.ABCTestEntityLocalization"));

	public ABCTestEntityLocalizationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _abcTestEntityLocalizationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAbcTestEntityLocalizationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _abcTestEntityLocalizationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ABCTestEntityLocalization.class;
	}

	@Override
	public String getModelClassName() {
		return ABCTestEntityLocalization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("mvccVersion", getMvccVersion());
		attributes.put("abcTestEntityLocalizationId",
			getAbcTestEntityLocalizationId());
		attributes.put("companyId", getCompanyId());
		attributes.put("abcTestEntityId", getAbcTestEntityId());
		attributes.put("languageId", getLanguageId());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("groupId", getGroupId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long mvccVersion = (Long)attributes.get("mvccVersion");

		if (mvccVersion != null) {
			setMvccVersion(mvccVersion);
		}

		Long abcTestEntityLocalizationId = (Long)attributes.get(
				"abcTestEntityLocalizationId");

		if (abcTestEntityLocalizationId != null) {
			setAbcTestEntityLocalizationId(abcTestEntityLocalizationId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String abcTestEntityId = (String)attributes.get("abcTestEntityId");

		if (abcTestEntityId != null) {
			setAbcTestEntityId(abcTestEntityId);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public long getAbcTestEntityLocalizationId() {
		return _abcTestEntityLocalizationId;
	}

	@Override
	public void setAbcTestEntityLocalizationId(long abcTestEntityLocalizationId) {
		_abcTestEntityLocalizationId = abcTestEntityLocalizationId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public String getAbcTestEntityId() {
		if (_abcTestEntityId == null) {
			return StringPool.BLANK;
		}
		else {
			return _abcTestEntityId;
		}
	}

	@Override
	public void setAbcTestEntityId(String abcTestEntityId) {
		_columnBitmask |= ABCTESTENTITYID_COLUMN_BITMASK;

		if (_originalAbcTestEntityId == null) {
			_originalAbcTestEntityId = _abcTestEntityId;
		}

		_abcTestEntityId = abcTestEntityId;
	}

	public String getOriginalAbcTestEntityId() {
		return GetterUtil.getString(_originalAbcTestEntityId);
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_columnBitmask |= LANGUAGEID_COLUMN_BITMASK;

		if (_originalLanguageId == null) {
			_originalLanguageId = _languageId;
		}

		_languageId = languageId;
	}

	public String getOriginalLanguageId() {
		return GetterUtil.getString(_originalLanguageId);
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ABCTestEntityLocalization.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ABCTestEntityLocalization toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ABCTestEntityLocalization)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ABCTestEntityLocalizationImpl abcTestEntityLocalizationImpl = new ABCTestEntityLocalizationImpl();

		abcTestEntityLocalizationImpl.setMvccVersion(getMvccVersion());
		abcTestEntityLocalizationImpl.setAbcTestEntityLocalizationId(getAbcTestEntityLocalizationId());
		abcTestEntityLocalizationImpl.setCompanyId(getCompanyId());
		abcTestEntityLocalizationImpl.setAbcTestEntityId(getAbcTestEntityId());
		abcTestEntityLocalizationImpl.setLanguageId(getLanguageId());
		abcTestEntityLocalizationImpl.setName(getName());
		abcTestEntityLocalizationImpl.setDescription(getDescription());
		abcTestEntityLocalizationImpl.setGroupId(getGroupId());

		abcTestEntityLocalizationImpl.resetOriginalValues();

		return abcTestEntityLocalizationImpl;
	}

	@Override
	public int compareTo(ABCTestEntityLocalization abcTestEntityLocalization) {
		int value = 0;

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ABCTestEntityLocalization)) {
			return false;
		}

		ABCTestEntityLocalization abcTestEntityLocalization = (ABCTestEntityLocalization)obj;

		long primaryKey = abcTestEntityLocalization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ABCTestEntityLocalizationModelImpl abcTestEntityLocalizationModelImpl = this;

		abcTestEntityLocalizationModelImpl._originalAbcTestEntityId = abcTestEntityLocalizationModelImpl._abcTestEntityId;

		abcTestEntityLocalizationModelImpl._originalLanguageId = abcTestEntityLocalizationModelImpl._languageId;

		abcTestEntityLocalizationModelImpl._originalName = abcTestEntityLocalizationModelImpl._name;

		abcTestEntityLocalizationModelImpl._originalGroupId = abcTestEntityLocalizationModelImpl._groupId;

		abcTestEntityLocalizationModelImpl._setOriginalGroupId = false;

		abcTestEntityLocalizationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ABCTestEntityLocalization> toCacheModel() {
		ABCTestEntityLocalizationCacheModel abcTestEntityLocalizationCacheModel = new ABCTestEntityLocalizationCacheModel();

		abcTestEntityLocalizationCacheModel.mvccVersion = getMvccVersion();

		abcTestEntityLocalizationCacheModel.abcTestEntityLocalizationId = getAbcTestEntityLocalizationId();

		abcTestEntityLocalizationCacheModel.companyId = getCompanyId();

		abcTestEntityLocalizationCacheModel.abcTestEntityId = getAbcTestEntityId();

		String abcTestEntityId = abcTestEntityLocalizationCacheModel.abcTestEntityId;

		if ((abcTestEntityId != null) && (abcTestEntityId.length() == 0)) {
			abcTestEntityLocalizationCacheModel.abcTestEntityId = null;
		}

		abcTestEntityLocalizationCacheModel.languageId = getLanguageId();

		String languageId = abcTestEntityLocalizationCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			abcTestEntityLocalizationCacheModel.languageId = null;
		}

		abcTestEntityLocalizationCacheModel.name = getName();

		String name = abcTestEntityLocalizationCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			abcTestEntityLocalizationCacheModel.name = null;
		}

		abcTestEntityLocalizationCacheModel.description = getDescription();

		String description = abcTestEntityLocalizationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			abcTestEntityLocalizationCacheModel.description = null;
		}

		abcTestEntityLocalizationCacheModel.groupId = getGroupId();

		return abcTestEntityLocalizationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{mvccVersion=");
		sb.append(getMvccVersion());
		sb.append(", abcTestEntityLocalizationId=");
		sb.append(getAbcTestEntityLocalizationId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", abcTestEntityId=");
		sb.append(getAbcTestEntityId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.kernel.model.ABCTestEntityLocalization");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>mvccVersion</column-name><column-value><![CDATA[");
		sb.append(getMvccVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>abcTestEntityLocalizationId</column-name><column-value><![CDATA[");
		sb.append(getAbcTestEntityLocalizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>abcTestEntityId</column-name><column-value><![CDATA[");
		sb.append(getAbcTestEntityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ABCTestEntityLocalization.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ABCTestEntityLocalization.class
		};
	private long _mvccVersion;
	private long _abcTestEntityLocalizationId;
	private long _companyId;
	private String _abcTestEntityId;
	private String _originalAbcTestEntityId;
	private String _languageId;
	private String _originalLanguageId;
	private String _name;
	private String _originalName;
	private String _description;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _columnBitmask;
	private ABCTestEntityLocalization _escapedModel;
}