/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.ABCTestEntity;
import com.liferay.portal.kernel.model.ABCTestEntityLocalization;
import com.liferay.portal.kernel.model.ABCTestEntityModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ABCTestEntityLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * The base model implementation for the ABCTestEntity service. Represents a row in the &quot;ABCTestEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ABCTestEntityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ABCTestEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ABCTestEntityImpl
 * @see ABCTestEntity
 * @see ABCTestEntityModel
 * @generated
 */
@ProviderType
public class ABCTestEntityModelImpl extends BaseModelImpl<ABCTestEntity>
	implements ABCTestEntityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a abc test entity model instance should use the {@link ABCTestEntity} interface instead.
	 */
	public static final String TABLE_NAME = "ABCTestEntity";
	public static final Object[][] TABLE_COLUMNS = {
			{ "mvccVersion", Types.BIGINT },
			{ "abcTestEntityId", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "defaultLanguageId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("abcTestEntityId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table ABCTestEntity (mvccVersion LONG default 0 not null,abcTestEntityId VARCHAR(75) not null primary key,companyId LONG,groupId LONG,defaultLanguageId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ABCTestEntity";
	public static final String ORDER_BY_JPQL = " ORDER BY abcTestEntity.abcTestEntityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ABCTestEntity.abcTestEntityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portal.kernel.model.ABCTestEntity"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portal.kernel.model.ABCTestEntity"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portal.kernel.model.ABCTestEntity"));

	public ABCTestEntityModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _abcTestEntityId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setAbcTestEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _abcTestEntityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ABCTestEntity.class;
	}

	@Override
	public String getModelClassName() {
		return ABCTestEntity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("mvccVersion", getMvccVersion());
		attributes.put("abcTestEntityId", getAbcTestEntityId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("defaultLanguageId", getDefaultLanguageId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long mvccVersion = (Long)attributes.get("mvccVersion");

		if (mvccVersion != null) {
			setMvccVersion(mvccVersion);
		}

		String abcTestEntityId = (String)attributes.get("abcTestEntityId");

		if (abcTestEntityId != null) {
			setAbcTestEntityId(abcTestEntityId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		String defaultLanguageId = (String)attributes.get("defaultLanguageId");

		if (defaultLanguageId != null) {
			setDefaultLanguageId(defaultLanguageId);
		}
	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<ABCTestEntityLocalization> abcTestEntityLocalizations = ABCTestEntityLocalServiceUtil.getABCTestEntityLocalizations(getPrimaryKey());

		String[] availableLanguageIds = new String[abcTestEntityLocalizations.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			ABCTestEntityLocalization abcTestEntityLocalization = abcTestEntityLocalizations.get(i);

			availableLanguageIds[i] = abcTestEntityLocalization.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getName() {
		return getName(getDefaultLanguageId(), false);
	}

	@Override
	public String getName(String languageId) {
		return getName(languageId, true);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getName(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getName(languageId);
	}

	@Override
	public String getNameMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToNameMap(),
			getDefaultLanguageId(), "Name");
	}

	@Override
	public Map<String, String> getLanguageIdToNameMap() {
		Map<String, String> languageIdToNameMap = new HashMap<String, String>();

		List<ABCTestEntityLocalization> abcTestEntityLocalizations = ABCTestEntityLocalServiceUtil.getABCTestEntityLocalizations(getPrimaryKey());

		for (ABCTestEntityLocalization abcTestEntityLocalization : abcTestEntityLocalizations) {
			languageIdToNameMap.put(abcTestEntityLocalization.getLanguageId(),
				abcTestEntityLocalization.getName());
		}

		return languageIdToNameMap;
	}

	private String _getName(String languageId) {
		ABCTestEntityLocalization abcTestEntityLocalization = ABCTestEntityLocalServiceUtil.fetchABCTestEntityLocalization(getPrimaryKey(),
				languageId);

		if (abcTestEntityLocalization == null) {
			return StringPool.BLANK;
		}

		return abcTestEntityLocalization.getName();
	}

	@Override
	public String getDescription() {
		return getDescription(getDefaultLanguageId(), false);
	}

	@Override
	public String getDescription(String languageId) {
		return getDescription(languageId, true);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getDescription(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getDescription(languageId);
	}

	@Override
	public String getDescriptionMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToDescriptionMap(),
			getDefaultLanguageId(), "Description");
	}

	@Override
	public Map<String, String> getLanguageIdToDescriptionMap() {
		Map<String, String> languageIdToDescriptionMap = new HashMap<String, String>();

		List<ABCTestEntityLocalization> abcTestEntityLocalizations = ABCTestEntityLocalServiceUtil.getABCTestEntityLocalizations(getPrimaryKey());

		for (ABCTestEntityLocalization abcTestEntityLocalization : abcTestEntityLocalizations) {
			languageIdToDescriptionMap.put(abcTestEntityLocalization.getLanguageId(),
				abcTestEntityLocalization.getDescription());
		}

		return languageIdToDescriptionMap;
	}

	private String _getDescription(String languageId) {
		ABCTestEntityLocalization abcTestEntityLocalization = ABCTestEntityLocalServiceUtil.fetchABCTestEntityLocalization(getPrimaryKey(),
				languageId);

		if (abcTestEntityLocalization == null) {
			return StringPool.BLANK;
		}

		return abcTestEntityLocalization.getDescription();
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public String getAbcTestEntityId() {
		if (_abcTestEntityId == null) {
			return StringPool.BLANK;
		}
		else {
			return _abcTestEntityId;
		}
	}

	@Override
	public void setAbcTestEntityId(String abcTestEntityId) {
		_abcTestEntityId = abcTestEntityId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		_defaultLanguageId = defaultLanguageId;
	}

	@Override
	public ABCTestEntity toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ABCTestEntity)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ABCTestEntityImpl abcTestEntityImpl = new ABCTestEntityImpl();

		abcTestEntityImpl.setMvccVersion(getMvccVersion());
		abcTestEntityImpl.setAbcTestEntityId(getAbcTestEntityId());
		abcTestEntityImpl.setCompanyId(getCompanyId());
		abcTestEntityImpl.setGroupId(getGroupId());
		abcTestEntityImpl.setDefaultLanguageId(getDefaultLanguageId());

		abcTestEntityImpl.resetOriginalValues();

		return abcTestEntityImpl;
	}

	@Override
	public int compareTo(ABCTestEntity abcTestEntity) {
		String primaryKey = abcTestEntity.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ABCTestEntity)) {
			return false;
		}

		ABCTestEntity abcTestEntity = (ABCTestEntity)obj;

		String primaryKey = abcTestEntity.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ABCTestEntity> toCacheModel() {
		ABCTestEntityCacheModel abcTestEntityCacheModel = new ABCTestEntityCacheModel();

		abcTestEntityCacheModel.mvccVersion = getMvccVersion();

		abcTestEntityCacheModel.abcTestEntityId = getAbcTestEntityId();

		String abcTestEntityId = abcTestEntityCacheModel.abcTestEntityId;

		if ((abcTestEntityId != null) && (abcTestEntityId.length() == 0)) {
			abcTestEntityCacheModel.abcTestEntityId = null;
		}

		abcTestEntityCacheModel.companyId = getCompanyId();

		abcTestEntityCacheModel.groupId = getGroupId();

		abcTestEntityCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = abcTestEntityCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			abcTestEntityCacheModel.defaultLanguageId = null;
		}

		return abcTestEntityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{mvccVersion=");
		sb.append(getMvccVersion());
		sb.append(", abcTestEntityId=");
		sb.append(getAbcTestEntityId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", defaultLanguageId=");
		sb.append(getDefaultLanguageId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.kernel.model.ABCTestEntity");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>mvccVersion</column-name><column-value><![CDATA[");
		sb.append(getMvccVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>abcTestEntityId</column-name><column-value><![CDATA[");
		sb.append(getAbcTestEntityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>defaultLanguageId</column-name><column-value><![CDATA[");
		sb.append(getDefaultLanguageId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ABCTestEntity.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ABCTestEntity.class
		};
	private long _mvccVersion;
	private String _abcTestEntityId;
	private long _companyId;
	private long _groupId;
	private String _defaultLanguageId;
	private ABCTestEntity _escapedModel;
}