/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Map;

/**
 * The base model interface for the ABCTestEntity service. Represents a row in the &quot;ABCTestEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.ABCTestEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.ABCTestEntityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ABCTestEntity
 * @see com.liferay.portal.model.impl.ABCTestEntityImpl
 * @see com.liferay.portal.model.impl.ABCTestEntityModelImpl
 * @generated
 */
@ProviderType
public interface ABCTestEntityModel extends BaseModel<ABCTestEntity>, MVCCModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a abc test entity model instance should use the {@link ABCTestEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this abc test entity.
	 *
	 * @return the primary key of this abc test entity
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this abc test entity.
	 *
	 * @param primaryKey the primary key of this abc test entity
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the mvcc version of this abc test entity.
	 *
	 * @return the mvcc version of this abc test entity
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this abc test entity.
	 *
	 * @param mvccVersion the mvcc version of this abc test entity
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the abc test entity ID of this abc test entity.
	 *
	 * @return the abc test entity ID of this abc test entity
	 */
	@AutoEscape
	public String getAbcTestEntityId();

	/**
	 * Sets the abc test entity ID of this abc test entity.
	 *
	 * @param abcTestEntityId the abc test entity ID of this abc test entity
	 */
	public void setAbcTestEntityId(String abcTestEntityId);

	/**
	 * Returns the company ID of this abc test entity.
	 *
	 * @return the company ID of this abc test entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this abc test entity.
	 *
	 * @param companyId the company ID of this abc test entity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this abc test entity.
	 *
	 * @return the group ID of this abc test entity
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this abc test entity.
	 *
	 * @param groupId the group ID of this abc test entity
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the default language ID of this abc test entity.
	 *
	 * @return the default language ID of this abc test entity
	 */
	@AutoEscape
	public String getDefaultLanguageId();

	/**
	 * Sets the default language ID of this abc test entity.
	 *
	 * @param defaultLanguageId the default language ID of this abc test entity
	 */
	public void setDefaultLanguageId(String defaultLanguageId);

	public String[] getAvailableLanguageIds();

	public String getName();

	public String getName(String languageId);

	public String getName(String languageId, boolean useDefault);

	public String getNameMapAsXML();

	public Map<String, String> getLanguageIdToNameMap();

	public String getDescription();

	public String getDescription(String languageId);

	public String getDescription(String languageId, boolean useDefault);

	public String getDescriptionMapAsXML();

	public Map<String, String> getLanguageIdToDescriptionMap();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ABCTestEntity abcTestEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ABCTestEntity> toCacheModel();

	@Override
	public ABCTestEntity toEscapedModel();

	@Override
	public ABCTestEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}