/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ABCTestEntityLocalization service. Represents a row in the &quot;ABCTestEntityLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.ABCTestEntityLocalizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.ABCTestEntityLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ABCTestEntityLocalization
 * @see com.liferay.portal.model.impl.ABCTestEntityLocalizationImpl
 * @see com.liferay.portal.model.impl.ABCTestEntityLocalizationModelImpl
 * @generated
 */
@ProviderType
public interface ABCTestEntityLocalizationModel extends BaseModel<ABCTestEntityLocalization>,
	MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a abc test entity localization model instance should use the {@link ABCTestEntityLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this abc test entity localization.
	 *
	 * @return the primary key of this abc test entity localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this abc test entity localization.
	 *
	 * @param primaryKey the primary key of this abc test entity localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this abc test entity localization.
	 *
	 * @return the mvcc version of this abc test entity localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this abc test entity localization.
	 *
	 * @param mvccVersion the mvcc version of this abc test entity localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the abc test entity localization ID of this abc test entity localization.
	 *
	 * @return the abc test entity localization ID of this abc test entity localization
	 */
	public long getAbcTestEntityLocalizationId();

	/**
	 * Sets the abc test entity localization ID of this abc test entity localization.
	 *
	 * @param abcTestEntityLocalizationId the abc test entity localization ID of this abc test entity localization
	 */
	public void setAbcTestEntityLocalizationId(long abcTestEntityLocalizationId);

	/**
	 * Returns the company ID of this abc test entity localization.
	 *
	 * @return the company ID of this abc test entity localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this abc test entity localization.
	 *
	 * @param companyId the company ID of this abc test entity localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the abc test entity ID of this abc test entity localization.
	 *
	 * @return the abc test entity ID of this abc test entity localization
	 */
	@AutoEscape
	public String getAbcTestEntityId();

	/**
	 * Sets the abc test entity ID of this abc test entity localization.
	 *
	 * @param abcTestEntityId the abc test entity ID of this abc test entity localization
	 */
	public void setAbcTestEntityId(String abcTestEntityId);

	/**
	 * Returns the language ID of this abc test entity localization.
	 *
	 * @return the language ID of this abc test entity localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this abc test entity localization.
	 *
	 * @param languageId the language ID of this abc test entity localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the name of this abc test entity localization.
	 *
	 * @return the name of this abc test entity localization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this abc test entity localization.
	 *
	 * @param name the name of this abc test entity localization
	 */
	public void setName(String name);

	/**
	 * Returns the description of this abc test entity localization.
	 *
	 * @return the description of this abc test entity localization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this abc test entity localization.
	 *
	 * @param description the description of this abc test entity localization
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this abc test entity localization.
	 *
	 * @return the group ID of this abc test entity localization
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this abc test entity localization.
	 *
	 * @param groupId the group ID of this abc test entity localization
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ABCTestEntityLocalization abcTestEntityLocalization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ABCTestEntityLocalization> toCacheModel();

	@Override
	public ABCTestEntityLocalization toEscapedModel();

	@Override
	public ABCTestEntityLocalization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}