/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.kernel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the GroupLocalization service. Represents a row in the &quot;GroupLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.GroupLocalizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.GroupLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GroupLocalization
 * @see com.liferay.portal.model.impl.GroupLocalizationImpl
 * @see com.liferay.portal.model.impl.GroupLocalizationModelImpl
 * @generated
 */
@ProviderType
public interface GroupLocalizationModel extends BaseModel<GroupLocalization>,
	MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a group localization model instance should use the {@link GroupLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this group localization.
	 *
	 * @return the primary key of this group localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this group localization.
	 *
	 * @param primaryKey the primary key of this group localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this group localization.
	 *
	 * @return the mvcc version of this group localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this group localization.
	 *
	 * @param mvccVersion the mvcc version of this group localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the group localization ID of this group localization.
	 *
	 * @return the group localization ID of this group localization
	 */
	public long getGroupLocalizationId();

	/**
	 * Sets the group localization ID of this group localization.
	 *
	 * @param groupLocalizationId the group localization ID of this group localization
	 */
	public void setGroupLocalizationId(long groupLocalizationId);

	/**
	 * Returns the company ID of this group localization.
	 *
	 * @return the company ID of this group localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this group localization.
	 *
	 * @param companyId the company ID of this group localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this group localization.
	 *
	 * @return the group ID of this group localization
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this group localization.
	 *
	 * @param groupId the group ID of this group localization
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the language ID of this group localization.
	 *
	 * @return the language ID of this group localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this group localization.
	 *
	 * @param languageId the language ID of this group localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the name of this group localization.
	 *
	 * @return the name of this group localization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this group localization.
	 *
	 * @param name the name of this group localization
	 */
	public void setName(String name);

	/**
	 * Returns the description of this group localization.
	 *
	 * @return the description of this group localization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this group localization.
	 *
	 * @param description the description of this group localization
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GroupLocalization groupLocalization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GroupLocalization> toCacheModel();

	@Override
	public GroupLocalization toEscapedModel();

	@Override
	public GroupLocalization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}