/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.dispatch.model.impl;

import com.liferay.dispatch.model.DispatchTask;
import com.liferay.dispatch.service.DispatchTaskLocalServiceUtil;

/**
 * The extended model base implementation for the DispatchTask service. Represents a row in the &quot;DispatchTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DispatchTaskImpl}.
 * </p>
 *
 * @author Matija Petanjek
 * @see DispatchTaskImpl
 * @see DispatchTask
 * @generated
 */
public abstract class DispatchTaskBaseImpl
	extends DispatchTaskModelImpl implements DispatchTask {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dispatch task model instance should use the <code>DispatchTask</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DispatchTaskLocalServiceUtil.addDispatchTask(this);
		}
		else {
			DispatchTaskLocalServiceUtil.updateDispatchTask(this);
		}
	}

}