/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.LargeAmountColumnEntity;
import com.liferay.portal.tools.service.builder.test.service.LargeAmountColumnEntityLocalService;
import com.liferay.portal.tools.service.builder.test.service.persistence.LargeAmountColumnEntityPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the large amount column entity local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.LargeAmountColumnEntityLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.LargeAmountColumnEntityLocalServiceImpl
 * @generated
 */
public abstract class LargeAmountColumnEntityLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, LargeAmountColumnEntityLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LargeAmountColumnEntityLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.LargeAmountColumnEntityLocalServiceUtil</code>.
	 */

	/**
	 * Adds the large amount column entity to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LargeAmountColumnEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param largeAmountColumnEntity the large amount column entity
	 * @return the large amount column entity that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LargeAmountColumnEntity addLargeAmountColumnEntity(
		LargeAmountColumnEntity largeAmountColumnEntity) {

		largeAmountColumnEntity.setNew(true);

		return largeAmountColumnEntityPersistence.update(
			largeAmountColumnEntity);
	}

	/**
	 * Creates a new large amount column entity with the primary key. Does not add the large amount column entity to the database.
	 *
	 * @param largeAmountColumnEntityId the primary key for the new large amount column entity
	 * @return the new large amount column entity
	 */
	@Override
	@Transactional(enabled = false)
	public LargeAmountColumnEntity createLargeAmountColumnEntity(
		long largeAmountColumnEntityId) {

		return largeAmountColumnEntityPersistence.create(
			largeAmountColumnEntityId);
	}

	/**
	 * Deletes the large amount column entity with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LargeAmountColumnEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param largeAmountColumnEntityId the primary key of the large amount column entity
	 * @return the large amount column entity that was removed
	 * @throws PortalException if a large amount column entity with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LargeAmountColumnEntity deleteLargeAmountColumnEntity(
			long largeAmountColumnEntityId)
		throws PortalException {

		return largeAmountColumnEntityPersistence.remove(
			largeAmountColumnEntityId);
	}

	/**
	 * Deletes the large amount column entity from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LargeAmountColumnEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param largeAmountColumnEntity the large amount column entity
	 * @return the large amount column entity that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LargeAmountColumnEntity deleteLargeAmountColumnEntity(
		LargeAmountColumnEntity largeAmountColumnEntity) {

		return largeAmountColumnEntityPersistence.remove(
			largeAmountColumnEntity);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return largeAmountColumnEntityPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LargeAmountColumnEntity.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return largeAmountColumnEntityPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.LargeAmountColumnEntityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return largeAmountColumnEntityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.LargeAmountColumnEntityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return largeAmountColumnEntityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return largeAmountColumnEntityPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return largeAmountColumnEntityPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LargeAmountColumnEntity fetchLargeAmountColumnEntity(
		long largeAmountColumnEntityId) {

		return largeAmountColumnEntityPersistence.fetchByPrimaryKey(
			largeAmountColumnEntityId);
	}

	/**
	 * Returns the large amount column entity with the primary key.
	 *
	 * @param largeAmountColumnEntityId the primary key of the large amount column entity
	 * @return the large amount column entity
	 * @throws PortalException if a large amount column entity with the primary key could not be found
	 */
	@Override
	public LargeAmountColumnEntity getLargeAmountColumnEntity(
			long largeAmountColumnEntityId)
		throws PortalException {

		return largeAmountColumnEntityPersistence.findByPrimaryKey(
			largeAmountColumnEntityId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			largeAmountColumnEntityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LargeAmountColumnEntity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"largeAmountColumnEntityId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			largeAmountColumnEntityLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			LargeAmountColumnEntity.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"largeAmountColumnEntityId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			largeAmountColumnEntityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LargeAmountColumnEntity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"largeAmountColumnEntityId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return largeAmountColumnEntityPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return largeAmountColumnEntityLocalService.
			deleteLargeAmountColumnEntity(
				(LargeAmountColumnEntity)persistedModel);
	}

	public BasePersistence<LargeAmountColumnEntity> getBasePersistence() {
		return largeAmountColumnEntityPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return largeAmountColumnEntityPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the large amount column entities.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.LargeAmountColumnEntityModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of large amount column entities
	 * @param end the upper bound of the range of large amount column entities (not inclusive)
	 * @return the range of large amount column entities
	 */
	@Override
	public List<LargeAmountColumnEntity> getLargeAmountColumnEntities(
		int start, int end) {

		return largeAmountColumnEntityPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of large amount column entities.
	 *
	 * @return the number of large amount column entities
	 */
	@Override
	public int getLargeAmountColumnEntitiesCount() {
		return largeAmountColumnEntityPersistence.countAll();
	}

	/**
	 * Updates the large amount column entity in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LargeAmountColumnEntityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param largeAmountColumnEntity the large amount column entity
	 * @return the large amount column entity that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LargeAmountColumnEntity updateLargeAmountColumnEntity(
		LargeAmountColumnEntity largeAmountColumnEntity) {

		return largeAmountColumnEntityPersistence.update(
			largeAmountColumnEntity);
	}

	/**
	 * Returns the large amount column entity local service.
	 *
	 * @return the large amount column entity local service
	 */
	public LargeAmountColumnEntityLocalService
		getLargeAmountColumnEntityLocalService() {

		return largeAmountColumnEntityLocalService;
	}

	/**
	 * Sets the large amount column entity local service.
	 *
	 * @param largeAmountColumnEntityLocalService the large amount column entity local service
	 */
	public void setLargeAmountColumnEntityLocalService(
		LargeAmountColumnEntityLocalService
			largeAmountColumnEntityLocalService) {

		this.largeAmountColumnEntityLocalService =
			largeAmountColumnEntityLocalService;
	}

	/**
	 * Returns the large amount column entity persistence.
	 *
	 * @return the large amount column entity persistence
	 */
	public LargeAmountColumnEntityPersistence
		getLargeAmountColumnEntityPersistence() {

		return largeAmountColumnEntityPersistence;
	}

	/**
	 * Sets the large amount column entity persistence.
	 *
	 * @param largeAmountColumnEntityPersistence the large amount column entity persistence
	 */
	public void setLargeAmountColumnEntityPersistence(
		LargeAmountColumnEntityPersistence largeAmountColumnEntityPersistence) {

		this.largeAmountColumnEntityPersistence =
			largeAmountColumnEntityPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.model.LargeAmountColumnEntity",
			largeAmountColumnEntityLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.model.LargeAmountColumnEntity");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LargeAmountColumnEntityLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LargeAmountColumnEntity.class;
	}

	protected String getModelClassName() {
		return LargeAmountColumnEntity.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				largeAmountColumnEntityPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = LargeAmountColumnEntityLocalService.class)
	protected LargeAmountColumnEntityLocalService
		largeAmountColumnEntityLocalService;

	@BeanReference(type = LargeAmountColumnEntityPersistence.class)
	protected LargeAmountColumnEntityPersistence
		largeAmountColumnEntityPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}