/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.LargeAmountColumnEntity;
import com.liferay.portal.tools.service.builder.test.service.LargeAmountColumnEntityService;
import com.liferay.portal.tools.service.builder.test.service.persistence.LargeAmountColumnEntityPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the large amount column entity remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.LargeAmountColumnEntityServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.LargeAmountColumnEntityServiceImpl
 * @generated
 */
public abstract class LargeAmountColumnEntityServiceBaseImpl
	extends BaseServiceImpl
	implements IdentifiableOSGiService, LargeAmountColumnEntityService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LargeAmountColumnEntityService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.LargeAmountColumnEntityServiceUtil</code>.
	 */

	/**
	 * Returns the large amount column entity local service.
	 *
	 * @return the large amount column entity local service
	 */
	public com.liferay.portal.tools.service.builder.test.service.
		LargeAmountColumnEntityLocalService
			getLargeAmountColumnEntityLocalService() {

		return largeAmountColumnEntityLocalService;
	}

	/**
	 * Sets the large amount column entity local service.
	 *
	 * @param largeAmountColumnEntityLocalService the large amount column entity local service
	 */
	public void setLargeAmountColumnEntityLocalService(
		com.liferay.portal.tools.service.builder.test.service.
			LargeAmountColumnEntityLocalService
				largeAmountColumnEntityLocalService) {

		this.largeAmountColumnEntityLocalService =
			largeAmountColumnEntityLocalService;
	}

	/**
	 * Returns the large amount column entity remote service.
	 *
	 * @return the large amount column entity remote service
	 */
	public LargeAmountColumnEntityService getLargeAmountColumnEntityService() {
		return largeAmountColumnEntityService;
	}

	/**
	 * Sets the large amount column entity remote service.
	 *
	 * @param largeAmountColumnEntityService the large amount column entity remote service
	 */
	public void setLargeAmountColumnEntityService(
		LargeAmountColumnEntityService largeAmountColumnEntityService) {

		this.largeAmountColumnEntityService = largeAmountColumnEntityService;
	}

	/**
	 * Returns the large amount column entity persistence.
	 *
	 * @return the large amount column entity persistence
	 */
	public LargeAmountColumnEntityPersistence
		getLargeAmountColumnEntityPersistence() {

		return largeAmountColumnEntityPersistence;
	}

	/**
	 * Sets the large amount column entity persistence.
	 *
	 * @param largeAmountColumnEntityPersistence the large amount column entity persistence
	 */
	public void setLargeAmountColumnEntityPersistence(
		LargeAmountColumnEntityPersistence largeAmountColumnEntityPersistence) {

		this.largeAmountColumnEntityPersistence =
			largeAmountColumnEntityPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LargeAmountColumnEntityService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LargeAmountColumnEntity.class;
	}

	protected String getModelClassName() {
		return LargeAmountColumnEntity.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				largeAmountColumnEntityPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(
		type = com.liferay.portal.tools.service.builder.test.service.LargeAmountColumnEntityLocalService.class
	)
	protected com.liferay.portal.tools.service.builder.test.service.
		LargeAmountColumnEntityLocalService largeAmountColumnEntityLocalService;

	@BeanReference(type = LargeAmountColumnEntityService.class)
	protected LargeAmountColumnEntityService largeAmountColumnEntityService;

	@BeanReference(type = LargeAmountColumnEntityPersistence.class)
	protected LargeAmountColumnEntityPersistence
		largeAmountColumnEntityPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}