sourceCompatibility = "1.8"
targetCompatibility = "1.8"

dependencies {
	compileOnly files("org.eclipse.osgi-debug.jar")
	compileOnly project(":core:osgi-service-tracker-collections")
	compileOnly project(":core:registry-api")
}

deployDependencies {
	from configurations.compileOnly
	include "org.eclipse.osgi-*.jar"
}

liferay {
	deployDir = file("${liferayHome}/osgi/core")
}