/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.view.count.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.view.count.model.ViewCountEntry;
import com.liferay.view.count.model.ViewCountEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the ViewCountEntry service. Represents a row in the &quot;ViewCountEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ViewCountEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViewCountEntryImpl}.
 * </p>
 *
 * @author Preston Crary
 * @see ViewCountEntryImpl
 * @generated
 */
@ProviderType
public class ViewCountEntryModelImpl
	extends BaseModelImpl<ViewCountEntry> implements ViewCountEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a view count entry model instance should use the <code>ViewCountEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ViewCountEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"viewCountEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"viewCount", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("viewCountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("viewCount", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ViewCountEntry (viewCountEntryId LONG not null primary key,companyId LONG,classNameId LONG,classPK LONG,viewCount LONG)";

	public static final String TABLE_SQL_DROP = "drop table ViewCountEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY viewCountEntry.viewCount DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ViewCountEntry.viewCount DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long VIEWCOUNT_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ViewCountEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _viewCountEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setViewCountEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _viewCountEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ViewCountEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ViewCountEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ViewCountEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ViewCountEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViewCountEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ViewCountEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ViewCountEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ViewCountEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ViewCountEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ViewCountEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ViewCountEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ViewCountEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ViewCountEntry.class.getClassLoader(), ViewCountEntry.class,
			ModelWrapper.class);

		try {
			Constructor<ViewCountEntry> constructor =
				(Constructor<ViewCountEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ViewCountEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ViewCountEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ViewCountEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ViewCountEntry, Object>>();
		Map<String, BiConsumer<ViewCountEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ViewCountEntry, ?>>();

		attributeGetterFunctions.put(
			"viewCountEntryId", ViewCountEntry::getViewCountEntryId);
		attributeSetterBiConsumers.put(
			"viewCountEntryId",
			(BiConsumer<ViewCountEntry, Long>)
				ViewCountEntry::setViewCountEntryId);
		attributeGetterFunctions.put("companyId", ViewCountEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ViewCountEntry, Long>)ViewCountEntry::setCompanyId);
		attributeGetterFunctions.put(
			"classNameId", ViewCountEntry::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<ViewCountEntry, Long>)ViewCountEntry::setClassNameId);
		attributeGetterFunctions.put("classPK", ViewCountEntry::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<ViewCountEntry, Long>)ViewCountEntry::setClassPK);
		attributeGetterFunctions.put("viewCount", ViewCountEntry::getViewCount);
		attributeSetterBiConsumers.put(
			"viewCount",
			(BiConsumer<ViewCountEntry, Long>)ViewCountEntry::setViewCount);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getViewCountEntryId() {
		return _viewCountEntryId;
	}

	@Override
	public void setViewCountEntryId(long viewCountEntryId) {
		_viewCountEntryId = viewCountEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@Override
	public long getViewCount() {
		return _viewCount;
	}

	@Override
	public void setViewCount(long viewCount) {
		_columnBitmask = -1L;

		_viewCount = viewCount;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ViewCountEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ViewCountEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ViewCountEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ViewCountEntryImpl viewCountEntryImpl = new ViewCountEntryImpl();

		viewCountEntryImpl.setViewCountEntryId(getViewCountEntryId());
		viewCountEntryImpl.setCompanyId(getCompanyId());
		viewCountEntryImpl.setClassNameId(getClassNameId());
		viewCountEntryImpl.setClassPK(getClassPK());
		viewCountEntryImpl.setViewCount(getViewCount());

		viewCountEntryImpl.resetOriginalValues();

		return viewCountEntryImpl;
	}

	@Override
	public int compareTo(ViewCountEntry viewCountEntry) {
		int value = 0;

		if (getViewCount() < viewCountEntry.getViewCount()) {
			value = -1;
		}
		else if (getViewCount() > viewCountEntry.getViewCount()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ViewCountEntry)) {
			return false;
		}

		ViewCountEntry viewCountEntry = (ViewCountEntry)obj;

		long primaryKey = viewCountEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ViewCountEntryModelImpl viewCountEntryModelImpl = this;

		viewCountEntryModelImpl._originalCompanyId =
			viewCountEntryModelImpl._companyId;

		viewCountEntryModelImpl._setOriginalCompanyId = false;

		viewCountEntryModelImpl._originalClassNameId =
			viewCountEntryModelImpl._classNameId;

		viewCountEntryModelImpl._setOriginalClassNameId = false;

		viewCountEntryModelImpl._originalClassPK =
			viewCountEntryModelImpl._classPK;

		viewCountEntryModelImpl._setOriginalClassPK = false;

		viewCountEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ViewCountEntry> toCacheModel() {
		ViewCountEntryCacheModel viewCountEntryCacheModel =
			new ViewCountEntryCacheModel();

		viewCountEntryCacheModel.viewCountEntryId = getViewCountEntryId();

		viewCountEntryCacheModel.companyId = getCompanyId();

		viewCountEntryCacheModel.classNameId = getClassNameId();

		viewCountEntryCacheModel.classPK = getClassPK();

		viewCountEntryCacheModel.viewCount = getViewCount();

		return viewCountEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ViewCountEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ViewCountEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViewCountEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ViewCountEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ViewCountEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ViewCountEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViewCountEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ViewCountEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ViewCountEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _viewCountEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private long _viewCount;
	private long _columnBitmask;
	private ViewCountEntry _escapedModel;

}