/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LargeAmountColumnEntity service. Represents a row in the &quot;LargeAmountColumnEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.LargeAmountColumnEntityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.LargeAmountColumnEntityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LargeAmountColumnEntity
 * @generated
 */
@ProviderType
public interface LargeAmountColumnEntityModel
	extends BaseModel<LargeAmountColumnEntity> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a large amount column entity model instance should use the {@link LargeAmountColumnEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this large amount column entity.
	 *
	 * @return the primary key of this large amount column entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this large amount column entity.
	 *
	 * @param primaryKey the primary key of this large amount column entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the large amount column entity ID of this large amount column entity.
	 *
	 * @return the large amount column entity ID of this large amount column entity
	 */
	public long getLargeAmountColumnEntityId();

	/**
	 * Sets the large amount column entity ID of this large amount column entity.
	 *
	 * @param largeAmountColumnEntityId the large amount column entity ID of this large amount column entity
	 */
	public void setLargeAmountColumnEntityId(long largeAmountColumnEntityId);

	/**
	 * Returns the column1 of this large amount column entity.
	 *
	 * @return the column1 of this large amount column entity
	 */
	public int getColumn1();

	/**
	 * Sets the column1 of this large amount column entity.
	 *
	 * @param column1 the column1 of this large amount column entity
	 */
	public void setColumn1(int column1);

	/**
	 * Returns the column2 of this large amount column entity.
	 *
	 * @return the column2 of this large amount column entity
	 */
	public int getColumn2();

	/**
	 * Sets the column2 of this large amount column entity.
	 *
	 * @param column2 the column2 of this large amount column entity
	 */
	public void setColumn2(int column2);

	/**
	 * Returns the column3 of this large amount column entity.
	 *
	 * @return the column3 of this large amount column entity
	 */
	public int getColumn3();

	/**
	 * Sets the column3 of this large amount column entity.
	 *
	 * @param column3 the column3 of this large amount column entity
	 */
	public void setColumn3(int column3);

	/**
	 * Returns the column4 of this large amount column entity.
	 *
	 * @return the column4 of this large amount column entity
	 */
	public int getColumn4();

	/**
	 * Sets the column4 of this large amount column entity.
	 *
	 * @param column4 the column4 of this large amount column entity
	 */
	public void setColumn4(int column4);

	/**
	 * Returns the column5 of this large amount column entity.
	 *
	 * @return the column5 of this large amount column entity
	 */
	public int getColumn5();

	/**
	 * Sets the column5 of this large amount column entity.
	 *
	 * @param column5 the column5 of this large amount column entity
	 */
	public void setColumn5(int column5);

	/**
	 * Returns the column6 of this large amount column entity.
	 *
	 * @return the column6 of this large amount column entity
	 */
	public int getColumn6();

	/**
	 * Sets the column6 of this large amount column entity.
	 *
	 * @param column6 the column6 of this large amount column entity
	 */
	public void setColumn6(int column6);

	/**
	 * Returns the column7 of this large amount column entity.
	 *
	 * @return the column7 of this large amount column entity
	 */
	public int getColumn7();

	/**
	 * Sets the column7 of this large amount column entity.
	 *
	 * @param column7 the column7 of this large amount column entity
	 */
	public void setColumn7(int column7);

	/**
	 * Returns the column8 of this large amount column entity.
	 *
	 * @return the column8 of this large amount column entity
	 */
	public int getColumn8();

	/**
	 * Sets the column8 of this large amount column entity.
	 *
	 * @param column8 the column8 of this large amount column entity
	 */
	public void setColumn8(int column8);

	/**
	 * Returns the column9 of this large amount column entity.
	 *
	 * @return the column9 of this large amount column entity
	 */
	public int getColumn9();

	/**
	 * Sets the column9 of this large amount column entity.
	 *
	 * @param column9 the column9 of this large amount column entity
	 */
	public void setColumn9(int column9);

	/**
	 * Returns the column10 of this large amount column entity.
	 *
	 * @return the column10 of this large amount column entity
	 */
	public int getColumn10();

	/**
	 * Sets the column10 of this large amount column entity.
	 *
	 * @param column10 the column10 of this large amount column entity
	 */
	public void setColumn10(int column10);

	/**
	 * Returns the column11 of this large amount column entity.
	 *
	 * @return the column11 of this large amount column entity
	 */
	public int getColumn11();

	/**
	 * Sets the column11 of this large amount column entity.
	 *
	 * @param column11 the column11 of this large amount column entity
	 */
	public void setColumn11(int column11);

	/**
	 * Returns the column12 of this large amount column entity.
	 *
	 * @return the column12 of this large amount column entity
	 */
	public int getColumn12();

	/**
	 * Sets the column12 of this large amount column entity.
	 *
	 * @param column12 the column12 of this large amount column entity
	 */
	public void setColumn12(int column12);

	/**
	 * Returns the column13 of this large amount column entity.
	 *
	 * @return the column13 of this large amount column entity
	 */
	public int getColumn13();

	/**
	 * Sets the column13 of this large amount column entity.
	 *
	 * @param column13 the column13 of this large amount column entity
	 */
	public void setColumn13(int column13);

	/**
	 * Returns the column14 of this large amount column entity.
	 *
	 * @return the column14 of this large amount column entity
	 */
	public int getColumn14();

	/**
	 * Sets the column14 of this large amount column entity.
	 *
	 * @param column14 the column14 of this large amount column entity
	 */
	public void setColumn14(int column14);

	/**
	 * Returns the column15 of this large amount column entity.
	 *
	 * @return the column15 of this large amount column entity
	 */
	public int getColumn15();

	/**
	 * Sets the column15 of this large amount column entity.
	 *
	 * @param column15 the column15 of this large amount column entity
	 */
	public void setColumn15(int column15);

	/**
	 * Returns the column16 of this large amount column entity.
	 *
	 * @return the column16 of this large amount column entity
	 */
	public int getColumn16();

	/**
	 * Sets the column16 of this large amount column entity.
	 *
	 * @param column16 the column16 of this large amount column entity
	 */
	public void setColumn16(int column16);

	/**
	 * Returns the column17 of this large amount column entity.
	 *
	 * @return the column17 of this large amount column entity
	 */
	public int getColumn17();

	/**
	 * Sets the column17 of this large amount column entity.
	 *
	 * @param column17 the column17 of this large amount column entity
	 */
	public void setColumn17(int column17);

	/**
	 * Returns the column18 of this large amount column entity.
	 *
	 * @return the column18 of this large amount column entity
	 */
	public int getColumn18();

	/**
	 * Sets the column18 of this large amount column entity.
	 *
	 * @param column18 the column18 of this large amount column entity
	 */
	public void setColumn18(int column18);

	/**
	 * Returns the column19 of this large amount column entity.
	 *
	 * @return the column19 of this large amount column entity
	 */
	public int getColumn19();

	/**
	 * Sets the column19 of this large amount column entity.
	 *
	 * @param column19 the column19 of this large amount column entity
	 */
	public void setColumn19(int column19);

	/**
	 * Returns the column20 of this large amount column entity.
	 *
	 * @return the column20 of this large amount column entity
	 */
	public int getColumn20();

	/**
	 * Sets the column20 of this large amount column entity.
	 *
	 * @param column20 the column20 of this large amount column entity
	 */
	public void setColumn20(int column20);

	/**
	 * Returns the column21 of this large amount column entity.
	 *
	 * @return the column21 of this large amount column entity
	 */
	public int getColumn21();

	/**
	 * Sets the column21 of this large amount column entity.
	 *
	 * @param column21 the column21 of this large amount column entity
	 */
	public void setColumn21(int column21);

	/**
	 * Returns the column22 of this large amount column entity.
	 *
	 * @return the column22 of this large amount column entity
	 */
	public int getColumn22();

	/**
	 * Sets the column22 of this large amount column entity.
	 *
	 * @param column22 the column22 of this large amount column entity
	 */
	public void setColumn22(int column22);

	/**
	 * Returns the column23 of this large amount column entity.
	 *
	 * @return the column23 of this large amount column entity
	 */
	public int getColumn23();

	/**
	 * Sets the column23 of this large amount column entity.
	 *
	 * @param column23 the column23 of this large amount column entity
	 */
	public void setColumn23(int column23);

	/**
	 * Returns the column24 of this large amount column entity.
	 *
	 * @return the column24 of this large amount column entity
	 */
	public int getColumn24();

	/**
	 * Sets the column24 of this large amount column entity.
	 *
	 * @param column24 the column24 of this large amount column entity
	 */
	public void setColumn24(int column24);

	/**
	 * Returns the column25 of this large amount column entity.
	 *
	 * @return the column25 of this large amount column entity
	 */
	public int getColumn25();

	/**
	 * Sets the column25 of this large amount column entity.
	 *
	 * @param column25 the column25 of this large amount column entity
	 */
	public void setColumn25(int column25);

	/**
	 * Returns the column26 of this large amount column entity.
	 *
	 * @return the column26 of this large amount column entity
	 */
	public int getColumn26();

	/**
	 * Sets the column26 of this large amount column entity.
	 *
	 * @param column26 the column26 of this large amount column entity
	 */
	public void setColumn26(int column26);

	/**
	 * Returns the column27 of this large amount column entity.
	 *
	 * @return the column27 of this large amount column entity
	 */
	public int getColumn27();

	/**
	 * Sets the column27 of this large amount column entity.
	 *
	 * @param column27 the column27 of this large amount column entity
	 */
	public void setColumn27(int column27);

	/**
	 * Returns the column28 of this large amount column entity.
	 *
	 * @return the column28 of this large amount column entity
	 */
	public int getColumn28();

	/**
	 * Sets the column28 of this large amount column entity.
	 *
	 * @param column28 the column28 of this large amount column entity
	 */
	public void setColumn28(int column28);

	/**
	 * Returns the column29 of this large amount column entity.
	 *
	 * @return the column29 of this large amount column entity
	 */
	public int getColumn29();

	/**
	 * Sets the column29 of this large amount column entity.
	 *
	 * @param column29 the column29 of this large amount column entity
	 */
	public void setColumn29(int column29);

	/**
	 * Returns the column30 of this large amount column entity.
	 *
	 * @return the column30 of this large amount column entity
	 */
	public int getColumn30();

	/**
	 * Sets the column30 of this large amount column entity.
	 *
	 * @param column30 the column30 of this large amount column entity
	 */
	public void setColumn30(int column30);

	/**
	 * Returns the column31 of this large amount column entity.
	 *
	 * @return the column31 of this large amount column entity
	 */
	public int getColumn31();

	/**
	 * Sets the column31 of this large amount column entity.
	 *
	 * @param column31 the column31 of this large amount column entity
	 */
	public void setColumn31(int column31);

	/**
	 * Returns the column32 of this large amount column entity.
	 *
	 * @return the column32 of this large amount column entity
	 */
	public int getColumn32();

	/**
	 * Sets the column32 of this large amount column entity.
	 *
	 * @param column32 the column32 of this large amount column entity
	 */
	public void setColumn32(int column32);

	/**
	 * Returns the column33 of this large amount column entity.
	 *
	 * @return the column33 of this large amount column entity
	 */
	public int getColumn33();

	/**
	 * Sets the column33 of this large amount column entity.
	 *
	 * @param column33 the column33 of this large amount column entity
	 */
	public void setColumn33(int column33);

	/**
	 * Returns the column34 of this large amount column entity.
	 *
	 * @return the column34 of this large amount column entity
	 */
	public int getColumn34();

	/**
	 * Sets the column34 of this large amount column entity.
	 *
	 * @param column34 the column34 of this large amount column entity
	 */
	public void setColumn34(int column34);

	/**
	 * Returns the column35 of this large amount column entity.
	 *
	 * @return the column35 of this large amount column entity
	 */
	public int getColumn35();

	/**
	 * Sets the column35 of this large amount column entity.
	 *
	 * @param column35 the column35 of this large amount column entity
	 */
	public void setColumn35(int column35);

	/**
	 * Returns the column36 of this large amount column entity.
	 *
	 * @return the column36 of this large amount column entity
	 */
	public int getColumn36();

	/**
	 * Sets the column36 of this large amount column entity.
	 *
	 * @param column36 the column36 of this large amount column entity
	 */
	public void setColumn36(int column36);

	/**
	 * Returns the column37 of this large amount column entity.
	 *
	 * @return the column37 of this large amount column entity
	 */
	public int getColumn37();

	/**
	 * Sets the column37 of this large amount column entity.
	 *
	 * @param column37 the column37 of this large amount column entity
	 */
	public void setColumn37(int column37);

	/**
	 * Returns the column38 of this large amount column entity.
	 *
	 * @return the column38 of this large amount column entity
	 */
	public int getColumn38();

	/**
	 * Sets the column38 of this large amount column entity.
	 *
	 * @param column38 the column38 of this large amount column entity
	 */
	public void setColumn38(int column38);

	/**
	 * Returns the column39 of this large amount column entity.
	 *
	 * @return the column39 of this large amount column entity
	 */
	public int getColumn39();

	/**
	 * Sets the column39 of this large amount column entity.
	 *
	 * @param column39 the column39 of this large amount column entity
	 */
	public void setColumn39(int column39);

	/**
	 * Returns the column40 of this large amount column entity.
	 *
	 * @return the column40 of this large amount column entity
	 */
	public int getColumn40();

	/**
	 * Sets the column40 of this large amount column entity.
	 *
	 * @param column40 the column40 of this large amount column entity
	 */
	public void setColumn40(int column40);

	/**
	 * Returns the column41 of this large amount column entity.
	 *
	 * @return the column41 of this large amount column entity
	 */
	public int getColumn41();

	/**
	 * Sets the column41 of this large amount column entity.
	 *
	 * @param column41 the column41 of this large amount column entity
	 */
	public void setColumn41(int column41);

	/**
	 * Returns the column42 of this large amount column entity.
	 *
	 * @return the column42 of this large amount column entity
	 */
	public int getColumn42();

	/**
	 * Sets the column42 of this large amount column entity.
	 *
	 * @param column42 the column42 of this large amount column entity
	 */
	public void setColumn42(int column42);

	/**
	 * Returns the column43 of this large amount column entity.
	 *
	 * @return the column43 of this large amount column entity
	 */
	public int getColumn43();

	/**
	 * Sets the column43 of this large amount column entity.
	 *
	 * @param column43 the column43 of this large amount column entity
	 */
	public void setColumn43(int column43);

	/**
	 * Returns the column44 of this large amount column entity.
	 *
	 * @return the column44 of this large amount column entity
	 */
	public int getColumn44();

	/**
	 * Sets the column44 of this large amount column entity.
	 *
	 * @param column44 the column44 of this large amount column entity
	 */
	public void setColumn44(int column44);

	/**
	 * Returns the column45 of this large amount column entity.
	 *
	 * @return the column45 of this large amount column entity
	 */
	public int getColumn45();

	/**
	 * Sets the column45 of this large amount column entity.
	 *
	 * @param column45 the column45 of this large amount column entity
	 */
	public void setColumn45(int column45);

	/**
	 * Returns the column46 of this large amount column entity.
	 *
	 * @return the column46 of this large amount column entity
	 */
	public int getColumn46();

	/**
	 * Sets the column46 of this large amount column entity.
	 *
	 * @param column46 the column46 of this large amount column entity
	 */
	public void setColumn46(int column46);

	/**
	 * Returns the column47 of this large amount column entity.
	 *
	 * @return the column47 of this large amount column entity
	 */
	public int getColumn47();

	/**
	 * Sets the column47 of this large amount column entity.
	 *
	 * @param column47 the column47 of this large amount column entity
	 */
	public void setColumn47(int column47);

	/**
	 * Returns the column48 of this large amount column entity.
	 *
	 * @return the column48 of this large amount column entity
	 */
	public int getColumn48();

	/**
	 * Sets the column48 of this large amount column entity.
	 *
	 * @param column48 the column48 of this large amount column entity
	 */
	public void setColumn48(int column48);

	/**
	 * Returns the column49 of this large amount column entity.
	 *
	 * @return the column49 of this large amount column entity
	 */
	public int getColumn49();

	/**
	 * Sets the column49 of this large amount column entity.
	 *
	 * @param column49 the column49 of this large amount column entity
	 */
	public void setColumn49(int column49);

	/**
	 * Returns the column50 of this large amount column entity.
	 *
	 * @return the column50 of this large amount column entity
	 */
	public int getColumn50();

	/**
	 * Sets the column50 of this large amount column entity.
	 *
	 * @param column50 the column50 of this large amount column entity
	 */
	public void setColumn50(int column50);

	/**
	 * Returns the column51 of this large amount column entity.
	 *
	 * @return the column51 of this large amount column entity
	 */
	public int getColumn51();

	/**
	 * Sets the column51 of this large amount column entity.
	 *
	 * @param column51 the column51 of this large amount column entity
	 */
	public void setColumn51(int column51);

	/**
	 * Returns the column52 of this large amount column entity.
	 *
	 * @return the column52 of this large amount column entity
	 */
	public int getColumn52();

	/**
	 * Sets the column52 of this large amount column entity.
	 *
	 * @param column52 the column52 of this large amount column entity
	 */
	public void setColumn52(int column52);

	/**
	 * Returns the column53 of this large amount column entity.
	 *
	 * @return the column53 of this large amount column entity
	 */
	public int getColumn53();

	/**
	 * Sets the column53 of this large amount column entity.
	 *
	 * @param column53 the column53 of this large amount column entity
	 */
	public void setColumn53(int column53);

	/**
	 * Returns the column54 of this large amount column entity.
	 *
	 * @return the column54 of this large amount column entity
	 */
	public int getColumn54();

	/**
	 * Sets the column54 of this large amount column entity.
	 *
	 * @param column54 the column54 of this large amount column entity
	 */
	public void setColumn54(int column54);

	/**
	 * Returns the column55 of this large amount column entity.
	 *
	 * @return the column55 of this large amount column entity
	 */
	public int getColumn55();

	/**
	 * Sets the column55 of this large amount column entity.
	 *
	 * @param column55 the column55 of this large amount column entity
	 */
	public void setColumn55(int column55);

	/**
	 * Returns the column56 of this large amount column entity.
	 *
	 * @return the column56 of this large amount column entity
	 */
	public int getColumn56();

	/**
	 * Sets the column56 of this large amount column entity.
	 *
	 * @param column56 the column56 of this large amount column entity
	 */
	public void setColumn56(int column56);

	/**
	 * Returns the column57 of this large amount column entity.
	 *
	 * @return the column57 of this large amount column entity
	 */
	public int getColumn57();

	/**
	 * Sets the column57 of this large amount column entity.
	 *
	 * @param column57 the column57 of this large amount column entity
	 */
	public void setColumn57(int column57);

	/**
	 * Returns the column58 of this large amount column entity.
	 *
	 * @return the column58 of this large amount column entity
	 */
	public int getColumn58();

	/**
	 * Sets the column58 of this large amount column entity.
	 *
	 * @param column58 the column58 of this large amount column entity
	 */
	public void setColumn58(int column58);

	/**
	 * Returns the column59 of this large amount column entity.
	 *
	 * @return the column59 of this large amount column entity
	 */
	public int getColumn59();

	/**
	 * Sets the column59 of this large amount column entity.
	 *
	 * @param column59 the column59 of this large amount column entity
	 */
	public void setColumn59(int column59);

	/**
	 * Returns the column60 of this large amount column entity.
	 *
	 * @return the column60 of this large amount column entity
	 */
	public int getColumn60();

	/**
	 * Sets the column60 of this large amount column entity.
	 *
	 * @param column60 the column60 of this large amount column entity
	 */
	public void setColumn60(int column60);

	/**
	 * Returns the column61 of this large amount column entity.
	 *
	 * @return the column61 of this large amount column entity
	 */
	public int getColumn61();

	/**
	 * Sets the column61 of this large amount column entity.
	 *
	 * @param column61 the column61 of this large amount column entity
	 */
	public void setColumn61(int column61);

	/**
	 * Returns the column62 of this large amount column entity.
	 *
	 * @return the column62 of this large amount column entity
	 */
	public int getColumn62();

	/**
	 * Sets the column62 of this large amount column entity.
	 *
	 * @param column62 the column62 of this large amount column entity
	 */
	public void setColumn62(int column62);

	/**
	 * Returns the column63 of this large amount column entity.
	 *
	 * @return the column63 of this large amount column entity
	 */
	public int getColumn63();

	/**
	 * Sets the column63 of this large amount column entity.
	 *
	 * @param column63 the column63 of this large amount column entity
	 */
	public void setColumn63(int column63);

	/**
	 * Returns the column64 of this large amount column entity.
	 *
	 * @return the column64 of this large amount column entity
	 */
	public int getColumn64();

	/**
	 * Sets the column64 of this large amount column entity.
	 *
	 * @param column64 the column64 of this large amount column entity
	 */
	public void setColumn64(int column64);

}