/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.version.VersionModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VersionedEntryContentVersion service. Represents a row in the &quot;VersionedEntryContentVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentVersionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VersionedEntryContentVersion
 * @see com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentVersionImpl
 * @see com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentVersionModelImpl
 * @generated
 */
@ProviderType
public interface VersionedEntryContentVersionModel extends BaseModel<VersionedEntryContentVersion>,
	VersionModel<VersionedEntryContent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a versioned entry content version model instance should use the {@link VersionedEntryContentVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this versioned entry content version.
	 *
	 * @return the primary key of this versioned entry content version
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this versioned entry content version.
	 *
	 * @param primaryKey the primary key of this versioned entry content version
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the versioned entry content version ID of this versioned entry content version.
	 *
	 * @return the versioned entry content version ID of this versioned entry content version
	 */
	public long getVersionedEntryContentVersionId();

	/**
	 * Sets the versioned entry content version ID of this versioned entry content version.
	 *
	 * @param versionedEntryContentVersionId the versioned entry content version ID of this versioned entry content version
	 */
	public void setVersionedEntryContentVersionId(
		long versionedEntryContentVersionId);

	/**
	 * Returns the version of this versioned entry content version.
	 *
	 * @return the version of this versioned entry content version
	 */
	@Override
	public int getVersion();

	/**
	 * Sets the version of this versioned entry content version.
	 *
	 * @param version the version of this versioned entry content version
	 */
	@Override
	public void setVersion(int version);

	/**
	 * Returns the versioned entry content ID of this versioned entry content version.
	 *
	 * @return the versioned entry content ID of this versioned entry content version
	 */
	public long getVersionedEntryContentId();

	/**
	 * Sets the versioned entry content ID of this versioned entry content version.
	 *
	 * @param versionedEntryContentId the versioned entry content ID of this versioned entry content version
	 */
	public void setVersionedEntryContentId(long versionedEntryContentId);

	/**
	 * Returns the versioned entry ID of this versioned entry content version.
	 *
	 * @return the versioned entry ID of this versioned entry content version
	 */
	public long getVersionedEntryId();

	/**
	 * Sets the versioned entry ID of this versioned entry content version.
	 *
	 * @param versionedEntryId the versioned entry ID of this versioned entry content version
	 */
	public void setVersionedEntryId(long versionedEntryId);

	/**
	 * Returns the language ID of this versioned entry content version.
	 *
	 * @return the language ID of this versioned entry content version
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this versioned entry content version.
	 *
	 * @param languageId the language ID of this versioned entry content version
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the content of this versioned entry content version.
	 *
	 * @return the content of this versioned entry content version
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this versioned entry content version.
	 *
	 * @param content the content of this versioned entry content version
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		VersionedEntryContentVersion versionedEntryContentVersion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VersionedEntryContentVersion> toCacheModel();

	@Override
	public VersionedEntryContentVersion toEscapedModel();

	@Override
	public VersionedEntryContentVersion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}