/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.version.VersionedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VersionedEntryContent service. Represents a row in the &quot;VersionedEntryContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VersionedEntryContent
 * @see com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentImpl
 * @see com.liferay.portal.tools.service.builder.test.model.impl.VersionedEntryContentModelImpl
 * @generated
 */
@ProviderType
public interface VersionedEntryContentModel extends BaseModel<VersionedEntryContent>,
	MVCCModel, VersionedModel<VersionedEntryContentVersion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a versioned entry content model instance should use the {@link VersionedEntryContent} interface instead.
	 */

	/**
	 * Returns the primary key of this versioned entry content.
	 *
	 * @return the primary key of this versioned entry content
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this versioned entry content.
	 *
	 * @param primaryKey the primary key of this versioned entry content
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this versioned entry content.
	 *
	 * @return the mvcc version of this versioned entry content
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this versioned entry content.
	 *
	 * @param mvccVersion the mvcc version of this versioned entry content
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the versioned entry content ID of this versioned entry content.
	 *
	 * @return the versioned entry content ID of this versioned entry content
	 */
	public long getVersionedEntryContentId();

	/**
	 * Sets the versioned entry content ID of this versioned entry content.
	 *
	 * @param versionedEntryContentId the versioned entry content ID of this versioned entry content
	 */
	public void setVersionedEntryContentId(long versionedEntryContentId);

	/**
	 * Returns the versioned entry ID of this versioned entry content.
	 *
	 * @return the versioned entry ID of this versioned entry content
	 */
	public long getVersionedEntryId();

	/**
	 * Sets the versioned entry ID of this versioned entry content.
	 *
	 * @param versionedEntryId the versioned entry ID of this versioned entry content
	 */
	public void setVersionedEntryId(long versionedEntryId);

	/**
	 * Returns the language ID of this versioned entry content.
	 *
	 * @return the language ID of this versioned entry content
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this versioned entry content.
	 *
	 * @param languageId the language ID of this versioned entry content
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the content of this versioned entry content.
	 *
	 * @return the content of this versioned entry content
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this versioned entry content.
	 *
	 * @param content the content of this versioned entry content
	 */
	public void setContent(String content);

	/**
	 * Returns the head ID of this versioned entry content.
	 *
	 * @return the head ID of this versioned entry content
	 */
	@Override
	public long getHeadId();

	/**
	 * Sets the head ID of this versioned entry content.
	 *
	 * @param headId the head ID of this versioned entry content
	 */
	@Override
	public void setHeadId(long headId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VersionedEntryContent versionedEntryContent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VersionedEntryContent> toCacheModel();

	@Override
	public VersionedEntryContent toEscapedModel();

	@Override
	public VersionedEntryContent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}