
module.snapshot.git.hash=1055028156fd491add2b791a402b2d5a6fa7e27f
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.portal.search.elasticsearch/1.0.0-SNAPSHOT/com.liferay.portal.search.elasticsearch-1.0.0-20150528.044721-1.jar
			