
module.snapshot.git.hash=96534e09384ac47b3732fcd9df4050e87ac284f8
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.dynamic.data.mapping.web/1.0.0-SNAPSHOT/com.liferay.dynamic.data.mapping.web-1.0.0-20150528.042158-2.jar
			