/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.security.password.model.HashAlgorithmEntry;
import com.liferay.portal.security.password.model.HashAlgorithmEntryModel;
import com.liferay.portal.security.password.model.HashAlgorithmEntrySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the HashAlgorithmEntry service. Represents a row in the &quot;HashAlgorithmEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>HashAlgorithmEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HashAlgorithmEntryImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see HashAlgorithmEntryImpl
 * @generated
 */
@JSON(strict = true)
public class HashAlgorithmEntryModelImpl
	extends BaseModelImpl<HashAlgorithmEntry>
	implements HashAlgorithmEntryModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hash algorithm entry model instance should use the <code>HashAlgorithmEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "HashAlgorithmEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"entryId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"meta", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("meta", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HashAlgorithmEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,entryId LONG not null primary key,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,meta VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table HashAlgorithmEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY hashAlgorithmEntry.entryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HashAlgorithmEntry.entryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long ENTRYID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static HashAlgorithmEntry toModel(HashAlgorithmEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		HashAlgorithmEntry model = new HashAlgorithmEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setEntryId(soapModel.getEntryId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setMeta(soapModel.getMeta());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<HashAlgorithmEntry> toModels(
		HashAlgorithmEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<HashAlgorithmEntry> models = new ArrayList<HashAlgorithmEntry>(
			soapModels.length);

		for (HashAlgorithmEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public HashAlgorithmEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HashAlgorithmEntry.class;
	}

	@Override
	public String getModelClassName() {
		return HashAlgorithmEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<HashAlgorithmEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<HashAlgorithmEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HashAlgorithmEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((HashAlgorithmEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<HashAlgorithmEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<HashAlgorithmEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(HashAlgorithmEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<HashAlgorithmEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<HashAlgorithmEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, HashAlgorithmEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			HashAlgorithmEntry.class.getClassLoader(), HashAlgorithmEntry.class,
			ModelWrapper.class);

		try {
			Constructor<HashAlgorithmEntry> constructor =
				(Constructor<HashAlgorithmEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<HashAlgorithmEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<HashAlgorithmEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<HashAlgorithmEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<HashAlgorithmEntry, Object>>();
		Map<String, BiConsumer<HashAlgorithmEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<HashAlgorithmEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", HashAlgorithmEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<HashAlgorithmEntry, Long>)
				HashAlgorithmEntry::setMvccVersion);
		attributeGetterFunctions.put("uuid", HashAlgorithmEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<HashAlgorithmEntry, String>)
				HashAlgorithmEntry::setUuid);
		attributeGetterFunctions.put("entryId", HashAlgorithmEntry::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<HashAlgorithmEntry, Long>)
				HashAlgorithmEntry::setEntryId);
		attributeGetterFunctions.put(
			"createDate", HashAlgorithmEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<HashAlgorithmEntry, Date>)
				HashAlgorithmEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", HashAlgorithmEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<HashAlgorithmEntry, Date>)
				HashAlgorithmEntry::setModifiedDate);
		attributeGetterFunctions.put("name", HashAlgorithmEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<HashAlgorithmEntry, String>)
				HashAlgorithmEntry::setName);
		attributeGetterFunctions.put("meta", HashAlgorithmEntry::getMeta);
		attributeSetterBiConsumers.put(
			"meta",
			(BiConsumer<HashAlgorithmEntry, String>)
				HashAlgorithmEntry::setMeta);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_entryId = entryId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getMeta() {
		if (_meta == null) {
			return "";
		}
		else {
			return _meta;
		}
	}

	@Override
	public void setMeta(String meta) {
		_meta = meta;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, HashAlgorithmEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HashAlgorithmEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, HashAlgorithmEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HashAlgorithmEntryImpl hashAlgorithmEntryImpl =
			new HashAlgorithmEntryImpl();

		hashAlgorithmEntryImpl.setMvccVersion(getMvccVersion());
		hashAlgorithmEntryImpl.setUuid(getUuid());
		hashAlgorithmEntryImpl.setEntryId(getEntryId());
		hashAlgorithmEntryImpl.setCreateDate(getCreateDate());
		hashAlgorithmEntryImpl.setModifiedDate(getModifiedDate());
		hashAlgorithmEntryImpl.setName(getName());
		hashAlgorithmEntryImpl.setMeta(getMeta());

		hashAlgorithmEntryImpl.resetOriginalValues();

		return hashAlgorithmEntryImpl;
	}

	@Override
	public int compareTo(HashAlgorithmEntry hashAlgorithmEntry) {
		long primaryKey = hashAlgorithmEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof HashAlgorithmEntry)) {
			return false;
		}

		HashAlgorithmEntry hashAlgorithmEntry = (HashAlgorithmEntry)obj;

		long primaryKey = hashAlgorithmEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		HashAlgorithmEntryModelImpl hashAlgorithmEntryModelImpl = this;

		hashAlgorithmEntryModelImpl._originalUuid =
			hashAlgorithmEntryModelImpl._uuid;

		hashAlgorithmEntryModelImpl._setModifiedDate = false;

		hashAlgorithmEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<HashAlgorithmEntry> toCacheModel() {
		HashAlgorithmEntryCacheModel hashAlgorithmEntryCacheModel =
			new HashAlgorithmEntryCacheModel();

		hashAlgorithmEntryCacheModel.mvccVersion = getMvccVersion();

		hashAlgorithmEntryCacheModel.uuid = getUuid();

		String uuid = hashAlgorithmEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			hashAlgorithmEntryCacheModel.uuid = null;
		}

		hashAlgorithmEntryCacheModel.entryId = getEntryId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			hashAlgorithmEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			hashAlgorithmEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			hashAlgorithmEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			hashAlgorithmEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		hashAlgorithmEntryCacheModel.name = getName();

		String name = hashAlgorithmEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			hashAlgorithmEntryCacheModel.name = null;
		}

		hashAlgorithmEntryCacheModel.meta = getMeta();

		String meta = hashAlgorithmEntryCacheModel.meta;

		if ((meta != null) && (meta.length() == 0)) {
			hashAlgorithmEntryCacheModel.meta = null;
		}

		return hashAlgorithmEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<HashAlgorithmEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<HashAlgorithmEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HashAlgorithmEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((HashAlgorithmEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<HashAlgorithmEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<HashAlgorithmEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HashAlgorithmEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((HashAlgorithmEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, HashAlgorithmEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _entryId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _meta;
	private long _columnBitmask;
	private HashAlgorithmEntry _escapedModel;

}