/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.model.impl;

import com.liferay.portal.security.password.model.PasswordMeta;
import com.liferay.portal.security.password.service.PasswordMetaLocalServiceUtil;

/**
 * The extended model base implementation for the PasswordMeta service. Represents a row in the &quot;PasswordMeta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PasswordMetaImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see PasswordMetaImpl
 * @see PasswordMeta
 * @generated
 */
public abstract class PasswordMetaBaseImpl
	extends PasswordMetaModelImpl implements PasswordMeta {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a password meta model instance should use the <code>PasswordMeta</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PasswordMetaLocalServiceUtil.addPasswordMeta(this);
		}
		else {
			PasswordMetaLocalServiceUtil.updatePasswordMeta(this);
		}
	}

}