
module.snapshot.git.hash=9e25e34ee6117234cdd3952d95cf6f2a8a676f9a
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.polls.api/1.0.0-SNAPSHOT/com.liferay.polls.api-1.0.0-20150528.042526-11.jar
			