
module.snapshot.git.hash=681e581da0c5dae979296b37f266fe47a38286f1
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.item.selector.web/1.0.0-SNAPSHOT/com.liferay.item.selector.web-1.0.0-20150528.042234-2.jar
			