
module.snapshot.git.hash=9cb3951574e9197f80f26bfb6c8e31261dff7111
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.service.access.control.profile.api/1.0.0-SNAPSHOT/com.liferay.service.access.control.profile.api-1.0.0-20150528.042645-2.jar
			