
module.snapshot.git.hash=dd605cb2fc49936fb74484db489e83588ed7f7cc
module.snapshot.url=http://cdn.repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.service.access.control.profile.web/1.0.0-SNAPSHOT/com.liferay.service.access.control.profile.web-1.0.0-20150528.042701-1.jar
			