dependencies {
	compileInclude group: "org.apache.pdfbox", name: "fontbox", version: "2.0.24"
	compileInclude group: "org.apache.pdfbox", name: "jbig2-imageio", version: "3.0.3"
	compileInclude group: "org.apache.pdfbox", name: "jempbox", version: "1.8.16"
	compileInclude group: "org.apache.pdfbox", name: "pdfbox", version: "2.0.24"
}