/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.model.version.VersionedModelInvocationHandler;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersionModel;

import java.io.Serializable;

import java.lang.reflect.Method;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VersionedEntryContentVersion service. Represents a row in the &quot;VersionedEntryContentVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VersionedEntryContentVersionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VersionedEntryContentVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VersionedEntryContentVersionImpl
 * @see VersionedEntryContentVersion
 * @see VersionedEntryContentVersionModel
 * @generated
 */
@ProviderType
public class VersionedEntryContentVersionModelImpl extends BaseModelImpl<VersionedEntryContentVersion>
	implements VersionedEntryContentVersionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a versioned entry content version model instance should use the {@link VersionedEntryContentVersion} interface instead.
	 */
	public static final String TABLE_NAME = "VersionedEntryContentVersion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "versionedEntryContentVersionId", Types.BIGINT },
			{ "version", Types.INTEGER },
			{ "versionedEntryContentId", Types.BIGINT },
			{ "versionedEntryId", Types.BIGINT },
			{ "languageId", Types.VARCHAR },
			{ "content", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("versionedEntryContentVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("versionedEntryContentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("versionedEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table VersionedEntryContentVersion (versionedEntryContentVersionId LONG not null primary key,version INTEGER,versionedEntryContentId LONG,versionedEntryId LONG,languageId VARCHAR(75) null,content VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table VersionedEntryContentVersion";
	public static final String ORDER_BY_JPQL = " ORDER BY versionedEntryContentVersion.version DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VersionedEntryContentVersion.version DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion"),
			true);
	public static final long LANGUAGEID_COLUMN_BITMASK = 1L;
	public static final long VERSION_COLUMN_BITMASK = 2L;
	public static final long VERSIONEDENTRYCONTENTID_COLUMN_BITMASK = 4L;
	public static final long VERSIONEDENTRYID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion"));

	public VersionedEntryContentVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _versionedEntryContentVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVersionedEntryContentVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _versionedEntryContentVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VersionedEntryContentVersion.class;
	}

	@Override
	public String getModelClassName() {
		return VersionedEntryContentVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("versionedEntryContentVersionId",
			getVersionedEntryContentVersionId());
		attributes.put("version", getVersion());
		attributes.put("versionedEntryContentId", getVersionedEntryContentId());
		attributes.put("versionedEntryId", getVersionedEntryId());
		attributes.put("languageId", getLanguageId());
		attributes.put("content", getContent());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long versionedEntryContentVersionId = (Long)attributes.get(
				"versionedEntryContentVersionId");

		if (versionedEntryContentVersionId != null) {
			setVersionedEntryContentVersionId(versionedEntryContentVersionId);
		}

		Integer version = (Integer)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		Long versionedEntryContentId = (Long)attributes.get(
				"versionedEntryContentId");

		if (versionedEntryContentId != null) {
			setVersionedEntryContentId(versionedEntryContentId);
		}

		Long versionedEntryId = (Long)attributes.get("versionedEntryId");

		if (versionedEntryId != null) {
			setVersionedEntryId(versionedEntryId);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}
	}

	@Override
	public long getVersionedModelId() {
		return getVersionedEntryContentId();
	}

	@Override
	public void populateVersionedModel(
		VersionedEntryContent versionedEntryContent) {
		versionedEntryContent.setVersionedEntryId(getVersionedEntryId());
		versionedEntryContent.setLanguageId(getLanguageId());
		versionedEntryContent.setContent(getContent());
	}

	@Override
	public void setVersionedModelId(long versionedEntryContentId) {
		setVersionedEntryContentId(versionedEntryContentId);
	}

	@Override
	public VersionedEntryContent toVersionedModel() {
		if (_versionedEntryContent == null) {
			_versionedEntryContent = (VersionedEntryContent)ProxyUtil.newProxyInstance(_classLoader,
					_versionedModelInterfaces,
					new VersionedModelInvocationHandler(this,
						_versionedModelMethodsMap));
		}

		return _versionedEntryContent;
	}

	@Override
	public long getVersionedEntryContentVersionId() {
		return _versionedEntryContentVersionId;
	}

	@Override
	public void setVersionedEntryContentVersionId(
		long versionedEntryContentVersionId) {
		_versionedEntryContentVersionId = versionedEntryContentVersionId;
	}

	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		_columnBitmask = -1L;

		if (!_setOriginalVersion) {
			_setOriginalVersion = true;

			_originalVersion = _version;
		}

		_version = version;
	}

	public int getOriginalVersion() {
		return _originalVersion;
	}

	@Override
	public long getVersionedEntryContentId() {
		return _versionedEntryContentId;
	}

	@Override
	public void setVersionedEntryContentId(long versionedEntryContentId) {
		_columnBitmask |= VERSIONEDENTRYCONTENTID_COLUMN_BITMASK;

		if (!_setOriginalVersionedEntryContentId) {
			_setOriginalVersionedEntryContentId = true;

			_originalVersionedEntryContentId = _versionedEntryContentId;
		}

		_versionedEntryContentId = versionedEntryContentId;
	}

	public long getOriginalVersionedEntryContentId() {
		return _originalVersionedEntryContentId;
	}

	@Override
	public long getVersionedEntryId() {
		return _versionedEntryId;
	}

	@Override
	public void setVersionedEntryId(long versionedEntryId) {
		_columnBitmask |= VERSIONEDENTRYID_COLUMN_BITMASK;

		if (!_setOriginalVersionedEntryId) {
			_setOriginalVersionedEntryId = true;

			_originalVersionedEntryId = _versionedEntryId;
		}

		_versionedEntryId = versionedEntryId;
	}

	public long getOriginalVersionedEntryId() {
		return _originalVersionedEntryId;
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_columnBitmask |= LANGUAGEID_COLUMN_BITMASK;

		if (_originalLanguageId == null) {
			_originalLanguageId = _languageId;
		}

		_languageId = languageId;
	}

	public String getOriginalLanguageId() {
		return GetterUtil.getString(_originalLanguageId);
	}

	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VersionedEntryContentVersion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VersionedEntryContentVersion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VersionedEntryContentVersion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VersionedEntryContentVersionImpl versionedEntryContentVersionImpl = new VersionedEntryContentVersionImpl();

		versionedEntryContentVersionImpl.setVersionedEntryContentVersionId(getVersionedEntryContentVersionId());
		versionedEntryContentVersionImpl.setVersion(getVersion());
		versionedEntryContentVersionImpl.setVersionedEntryContentId(getVersionedEntryContentId());
		versionedEntryContentVersionImpl.setVersionedEntryId(getVersionedEntryId());
		versionedEntryContentVersionImpl.setLanguageId(getLanguageId());
		versionedEntryContentVersionImpl.setContent(getContent());

		versionedEntryContentVersionImpl.resetOriginalValues();

		return versionedEntryContentVersionImpl;
	}

	@Override
	public int compareTo(
		VersionedEntryContentVersion versionedEntryContentVersion) {
		int value = 0;

		if (getVersion() < versionedEntryContentVersion.getVersion()) {
			value = -1;
		}
		else if (getVersion() > versionedEntryContentVersion.getVersion()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VersionedEntryContentVersion)) {
			return false;
		}

		VersionedEntryContentVersion versionedEntryContentVersion = (VersionedEntryContentVersion)obj;

		long primaryKey = versionedEntryContentVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VersionedEntryContentVersionModelImpl versionedEntryContentVersionModelImpl =
			this;

		versionedEntryContentVersionModelImpl._originalVersion = versionedEntryContentVersionModelImpl._version;

		versionedEntryContentVersionModelImpl._setOriginalVersion = false;

		versionedEntryContentVersionModelImpl._originalVersionedEntryContentId = versionedEntryContentVersionModelImpl._versionedEntryContentId;

		versionedEntryContentVersionModelImpl._setOriginalVersionedEntryContentId = false;

		versionedEntryContentVersionModelImpl._originalVersionedEntryId = versionedEntryContentVersionModelImpl._versionedEntryId;

		versionedEntryContentVersionModelImpl._setOriginalVersionedEntryId = false;

		versionedEntryContentVersionModelImpl._originalLanguageId = versionedEntryContentVersionModelImpl._languageId;

		versionedEntryContentVersionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VersionedEntryContentVersion> toCacheModel() {
		VersionedEntryContentVersionCacheModel versionedEntryContentVersionCacheModel =
			new VersionedEntryContentVersionCacheModel();

		versionedEntryContentVersionCacheModel.versionedEntryContentVersionId = getVersionedEntryContentVersionId();

		versionedEntryContentVersionCacheModel.version = getVersion();

		versionedEntryContentVersionCacheModel.versionedEntryContentId = getVersionedEntryContentId();

		versionedEntryContentVersionCacheModel.versionedEntryId = getVersionedEntryId();

		versionedEntryContentVersionCacheModel.languageId = getLanguageId();

		String languageId = versionedEntryContentVersionCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			versionedEntryContentVersionCacheModel.languageId = null;
		}

		versionedEntryContentVersionCacheModel.content = getContent();

		String content = versionedEntryContentVersionCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			versionedEntryContentVersionCacheModel.content = null;
		}

		return versionedEntryContentVersionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{versionedEntryContentVersionId=");
		sb.append(getVersionedEntryContentVersionId());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", versionedEntryContentId=");
		sb.append(getVersionedEntryContentId());
		sb.append(", versionedEntryId=");
		sb.append(getVersionedEntryId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", content=");
		sb.append(getContent());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>versionedEntryContentVersionId</column-name><column-value><![CDATA[");
		sb.append(getVersionedEntryContentVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versionedEntryContentId</column-name><column-value><![CDATA[");
		sb.append(getVersionedEntryContentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versionedEntryId</column-name><column-value><![CDATA[");
		sb.append(getVersionedEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VersionedEntryContentVersion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VersionedEntryContentVersion.class
		};
	private static final Map<Method, Method> _versionedModelMethodsMap = new HashMap<Method, Method>();
	private static final Class<?>[] _versionedModelInterfaces = new Class<?>[] {
			VersionedEntryContent.class
		};

	static {
		try {
			_versionedModelMethodsMap.put(VersionedEntryContent.class.getMethod(
					"getPrimaryKey"),
				VersionedEntryContentVersion.class.getMethod(
					"getVersionedModelId"));

			_versionedModelMethodsMap.put(VersionedEntryContent.class.getMethod(
					"getVersionedEntryContentId"),
				VersionedEntryContentVersion.class.getMethod(
					"getVersionedEntryContentId"));

			_versionedModelMethodsMap.put(VersionedEntryContent.class.getMethod(
					"getVersionedEntryId"),
				VersionedEntryContentVersion.class.getMethod(
					"getVersionedEntryId"));

			_versionedModelMethodsMap.put(VersionedEntryContent.class.getMethod(
					"getLanguageId"),
				VersionedEntryContentVersion.class.getMethod("getLanguageId"));

			_versionedModelMethodsMap.put(VersionedEntryContent.class.getMethod(
					"getContent"),
				VersionedEntryContentVersion.class.getMethod("getContent"));
		}
		catch (ReflectiveOperationException roe) {
			throw new ExceptionInInitializerError(roe);
		}
	}

	private volatile VersionedEntryContent _versionedEntryContent;
	private long _versionedEntryContentVersionId;
	private int _version;
	private int _originalVersion;
	private boolean _setOriginalVersion;
	private long _versionedEntryContentId;
	private long _originalVersionedEntryContentId;
	private boolean _setOriginalVersionedEntryContentId;
	private long _versionedEntryId;
	private long _originalVersionedEntryId;
	private boolean _setOriginalVersionedEntryId;
	private String _languageId;
	private String _originalLanguageId;
	private String _content;
	private long _columnBitmask;
	private VersionedEntryContentVersion _escapedModel;
}