/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentModel;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContentVersion;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VersionedEntryContent service. Represents a row in the &quot;VersionedEntryContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VersionedEntryContentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VersionedEntryContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VersionedEntryContentImpl
 * @see VersionedEntryContent
 * @see VersionedEntryContentModel
 * @generated
 */
@ProviderType
public class VersionedEntryContentModelImpl extends BaseModelImpl<VersionedEntryContent>
	implements VersionedEntryContentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a versioned entry content model instance should use the {@link VersionedEntryContent} interface instead.
	 */
	public static final String TABLE_NAME = "VersionedEntryContent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "mvccVersion", Types.BIGINT },
			{ "versionedEntryContentId", Types.BIGINT },
			{ "versionedEntryId", Types.BIGINT },
			{ "languageId", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "headId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("versionedEntryContentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("versionedEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("headId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table VersionedEntryContent (mvccVersion LONG default 0 not null,versionedEntryContentId LONG not null primary key,versionedEntryId LONG,languageId VARCHAR(75) null,content VARCHAR(75) null,headId LONG)";
	public static final String TABLE_SQL_DROP = "drop table VersionedEntryContent";
	public static final String ORDER_BY_JPQL = " ORDER BY versionedEntryContent.versionedEntryContentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VersionedEntryContent.versionedEntryContentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent"),
			true);
	public static final long HEADID_COLUMN_BITMASK = 1L;
	public static final long LANGUAGEID_COLUMN_BITMASK = 2L;
	public static final long VERSIONEDENTRYID_COLUMN_BITMASK = 4L;
	public static final long VERSIONEDENTRYCONTENTID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent"));

	public VersionedEntryContentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _versionedEntryContentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVersionedEntryContentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _versionedEntryContentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VersionedEntryContent.class;
	}

	@Override
	public String getModelClassName() {
		return VersionedEntryContent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("mvccVersion", getMvccVersion());
		attributes.put("versionedEntryContentId", getVersionedEntryContentId());
		attributes.put("versionedEntryId", getVersionedEntryId());
		attributes.put("languageId", getLanguageId());
		attributes.put("content", getContent());
		attributes.put("headId", getHeadId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long mvccVersion = (Long)attributes.get("mvccVersion");

		if (mvccVersion != null) {
			setMvccVersion(mvccVersion);
		}

		Long versionedEntryContentId = (Long)attributes.get(
				"versionedEntryContentId");

		if (versionedEntryContentId != null) {
			setVersionedEntryContentId(versionedEntryContentId);
		}

		Long versionedEntryId = (Long)attributes.get("versionedEntryId");

		if (versionedEntryId != null) {
			setVersionedEntryId(versionedEntryId);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		Long headId = (Long)attributes.get("headId");

		if (headId != null) {
			setHeadId(headId);
		}
	}

	@Override
	public boolean isDraft() {
		if (getHeadId() > 0) {
			return true;
		}

		return false;
	}

	@Override
	public void populateVersionModel(
		VersionedEntryContentVersion versionedEntryContentVersion) {
		versionedEntryContentVersion.setVersionedEntryId(getVersionedEntryId());
		versionedEntryContentVersion.setLanguageId(getLanguageId());
		versionedEntryContentVersion.setContent(getContent());
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public long getVersionedEntryContentId() {
		return _versionedEntryContentId;
	}

	@Override
	public void setVersionedEntryContentId(long versionedEntryContentId) {
		_versionedEntryContentId = versionedEntryContentId;
	}

	@Override
	public long getVersionedEntryId() {
		return _versionedEntryId;
	}

	@Override
	public void setVersionedEntryId(long versionedEntryId) {
		_columnBitmask |= VERSIONEDENTRYID_COLUMN_BITMASK;

		if (!_setOriginalVersionedEntryId) {
			_setOriginalVersionedEntryId = true;

			_originalVersionedEntryId = _versionedEntryId;
		}

		_versionedEntryId = versionedEntryId;
	}

	public long getOriginalVersionedEntryId() {
		return _originalVersionedEntryId;
	}

	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_columnBitmask |= LANGUAGEID_COLUMN_BITMASK;

		if (_originalLanguageId == null) {
			_originalLanguageId = _languageId;
		}

		_languageId = languageId;
	}

	public String getOriginalLanguageId() {
		return GetterUtil.getString(_originalLanguageId);
	}

	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@Override
	public long getHeadId() {
		return _headId;
	}

	@Override
	public void setHeadId(long headId) {
		_columnBitmask |= HEADID_COLUMN_BITMASK;

		if (!_setOriginalHeadId) {
			_setOriginalHeadId = true;

			_originalHeadId = _headId;
		}

		_headId = headId;
	}

	public long getOriginalHeadId() {
		return _originalHeadId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VersionedEntryContent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VersionedEntryContent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VersionedEntryContent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VersionedEntryContentImpl versionedEntryContentImpl = new VersionedEntryContentImpl();

		versionedEntryContentImpl.setMvccVersion(getMvccVersion());
		versionedEntryContentImpl.setVersionedEntryContentId(getVersionedEntryContentId());
		versionedEntryContentImpl.setVersionedEntryId(getVersionedEntryId());
		versionedEntryContentImpl.setLanguageId(getLanguageId());
		versionedEntryContentImpl.setContent(getContent());
		versionedEntryContentImpl.setHeadId(getHeadId());

		versionedEntryContentImpl.resetOriginalValues();

		return versionedEntryContentImpl;
	}

	@Override
	public int compareTo(VersionedEntryContent versionedEntryContent) {
		long primaryKey = versionedEntryContent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VersionedEntryContent)) {
			return false;
		}

		VersionedEntryContent versionedEntryContent = (VersionedEntryContent)obj;

		long primaryKey = versionedEntryContent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VersionedEntryContentModelImpl versionedEntryContentModelImpl = this;

		versionedEntryContentModelImpl._originalVersionedEntryId = versionedEntryContentModelImpl._versionedEntryId;

		versionedEntryContentModelImpl._setOriginalVersionedEntryId = false;

		versionedEntryContentModelImpl._originalLanguageId = versionedEntryContentModelImpl._languageId;

		versionedEntryContentModelImpl._originalHeadId = versionedEntryContentModelImpl._headId;

		versionedEntryContentModelImpl._setOriginalHeadId = false;

		versionedEntryContentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VersionedEntryContent> toCacheModel() {
		VersionedEntryContentCacheModel versionedEntryContentCacheModel = new VersionedEntryContentCacheModel();

		versionedEntryContentCacheModel.mvccVersion = getMvccVersion();

		versionedEntryContentCacheModel.versionedEntryContentId = getVersionedEntryContentId();

		versionedEntryContentCacheModel.versionedEntryId = getVersionedEntryId();

		versionedEntryContentCacheModel.languageId = getLanguageId();

		String languageId = versionedEntryContentCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			versionedEntryContentCacheModel.languageId = null;
		}

		versionedEntryContentCacheModel.content = getContent();

		String content = versionedEntryContentCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			versionedEntryContentCacheModel.content = null;
		}

		versionedEntryContentCacheModel.headId = getHeadId();

		return versionedEntryContentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{mvccVersion=");
		sb.append(getMvccVersion());
		sb.append(", versionedEntryContentId=");
		sb.append(getVersionedEntryContentId());
		sb.append(", versionedEntryId=");
		sb.append(getVersionedEntryId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", headId=");
		sb.append(getHeadId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>mvccVersion</column-name><column-value><![CDATA[");
		sb.append(getMvccVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versionedEntryContentId</column-name><column-value><![CDATA[");
		sb.append(getVersionedEntryContentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versionedEntryId</column-name><column-value><![CDATA[");
		sb.append(getVersionedEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>headId</column-name><column-value><![CDATA[");
		sb.append(getHeadId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VersionedEntryContent.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VersionedEntryContent.class
		};
	private long _mvccVersion;
	private long _versionedEntryContentId;
	private long _versionedEntryId;
	private long _originalVersionedEntryId;
	private boolean _setOriginalVersionedEntryId;
	private String _languageId;
	private String _originalLanguageId;
	private String _content;
	private long _headId;
	private long _originalHeadId;
	private boolean _setOriginalHeadId;
	private long _columnBitmask;
	private VersionedEntryContent _escapedModel;
}