/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntry;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryContent;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryModel;
import com.liferay.portal.tools.service.builder.test.model.VersionedEntryVersion;
import com.liferay.portal.tools.service.builder.test.service.VersionedEntryLocalServiceUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * The base model implementation for the VersionedEntry service. Represents a row in the &quot;VersionedEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VersionedEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VersionedEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VersionedEntryImpl
 * @see VersionedEntry
 * @see VersionedEntryModel
 * @generated
 */
@ProviderType
public class VersionedEntryModelImpl extends BaseModelImpl<VersionedEntry>
	implements VersionedEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a versioned entry model instance should use the {@link VersionedEntry} interface instead.
	 */
	public static final String TABLE_NAME = "VersionedEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "mvccVersion", Types.BIGINT },
			{ "versionedEntryId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "headId", Types.BIGINT },
			{ "defaultLanguageId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("versionedEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("headId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table VersionedEntry (mvccVersion LONG default 0 not null,versionedEntryId LONG not null primary key,groupId LONG,headId LONG,defaultLanguageId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table VersionedEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY versionedEntry.versionedEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VersionedEntry.versionedEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.model.VersionedEntry"),
			true);
	public static final long GROUPID_COLUMN_BITMASK = 1L;
	public static final long HEADID_COLUMN_BITMASK = 2L;
	public static final long VERSIONEDENTRYID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.VersionedEntry"));

	public VersionedEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _versionedEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVersionedEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _versionedEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VersionedEntry.class;
	}

	@Override
	public String getModelClassName() {
		return VersionedEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("mvccVersion", getMvccVersion());
		attributes.put("versionedEntryId", getVersionedEntryId());
		attributes.put("groupId", getGroupId());
		attributes.put("headId", getHeadId());
		attributes.put("defaultLanguageId", getDefaultLanguageId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long mvccVersion = (Long)attributes.get("mvccVersion");

		if (mvccVersion != null) {
			setMvccVersion(mvccVersion);
		}

		Long versionedEntryId = (Long)attributes.get("versionedEntryId");

		if (versionedEntryId != null) {
			setVersionedEntryId(versionedEntryId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long headId = (Long)attributes.get("headId");

		if (headId != null) {
			setHeadId(headId);
		}

		String defaultLanguageId = (String)attributes.get("defaultLanguageId");

		if (defaultLanguageId != null) {
			setDefaultLanguageId(defaultLanguageId);
		}
	}

	@Override
	public String[] getAvailableLanguageIds() {
		List<VersionedEntryContent> versionedEntryContents = VersionedEntryLocalServiceUtil.getVersionedEntryContents(getPrimaryKey());

		String[] availableLanguageIds = new String[versionedEntryContents.size()];

		for (int i = 0; i < availableLanguageIds.length; i++) {
			VersionedEntryContent versionedEntryContent = versionedEntryContents.get(i);

			availableLanguageIds[i] = versionedEntryContent.getLanguageId();
		}

		return availableLanguageIds;
	}

	@Override
	public String getContent() {
		return getContent(getDefaultLanguageId(), false);
	}

	@Override
	public String getContent(String languageId) {
		return getContent(languageId, true);
	}

	@Override
	public String getContent(String languageId, boolean useDefault) {
		if (useDefault) {
			return LocalizationUtil.getLocalization(new Function<String, String>() {
					@Override
					public String apply(String languageId) {
						return _getContent(languageId);
					}
				}, languageId, getDefaultLanguageId());
		}

		return _getContent(languageId);
	}

	@Override
	public String getContentMapAsXML() {
		return LocalizationUtil.getXml(getLanguageIdToContentMap(),
			getDefaultLanguageId(), "Content");
	}

	@Override
	public Map<String, String> getLanguageIdToContentMap() {
		Map<String, String> languageIdToContentMap = new HashMap<String, String>();

		List<VersionedEntryContent> versionedEntryContents = VersionedEntryLocalServiceUtil.getVersionedEntryContents(getPrimaryKey());

		for (VersionedEntryContent versionedEntryContent : versionedEntryContents) {
			languageIdToContentMap.put(versionedEntryContent.getLanguageId(),
				versionedEntryContent.getContent());
		}

		return languageIdToContentMap;
	}

	private String _getContent(String languageId) {
		VersionedEntryContent versionedEntryContent = VersionedEntryLocalServiceUtil.fetchVersionedEntryContent(getPrimaryKey(),
				languageId);

		if (versionedEntryContent == null) {
			return "";
		}

		return versionedEntryContent.getContent();
	}

	@Override
	public boolean isDraft() {
		if (getHeadId() > 0) {
			return true;
		}

		return false;
	}

	@Override
	public void populateVersionModel(
		VersionedEntryVersion versionedEntryVersion) {
		versionedEntryVersion.setGroupId(getGroupId());
		versionedEntryVersion.setDefaultLanguageId(getDefaultLanguageId());
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public long getVersionedEntryId() {
		return _versionedEntryId;
	}

	@Override
	public void setVersionedEntryId(long versionedEntryId) {
		_versionedEntryId = versionedEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getHeadId() {
		return _headId;
	}

	@Override
	public void setHeadId(long headId) {
		_columnBitmask |= HEADID_COLUMN_BITMASK;

		if (!_setOriginalHeadId) {
			_setOriginalHeadId = true;

			_originalHeadId = _headId;
		}

		_headId = headId;
	}

	public long getOriginalHeadId() {
		return _originalHeadId;
	}

	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		_defaultLanguageId = defaultLanguageId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VersionedEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VersionedEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VersionedEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VersionedEntryImpl versionedEntryImpl = new VersionedEntryImpl();

		versionedEntryImpl.setMvccVersion(getMvccVersion());
		versionedEntryImpl.setVersionedEntryId(getVersionedEntryId());
		versionedEntryImpl.setGroupId(getGroupId());
		versionedEntryImpl.setHeadId(getHeadId());
		versionedEntryImpl.setDefaultLanguageId(getDefaultLanguageId());

		versionedEntryImpl.resetOriginalValues();

		return versionedEntryImpl;
	}

	@Override
	public int compareTo(VersionedEntry versionedEntry) {
		long primaryKey = versionedEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VersionedEntry)) {
			return false;
		}

		VersionedEntry versionedEntry = (VersionedEntry)obj;

		long primaryKey = versionedEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VersionedEntryModelImpl versionedEntryModelImpl = this;

		versionedEntryModelImpl._originalGroupId = versionedEntryModelImpl._groupId;

		versionedEntryModelImpl._setOriginalGroupId = false;

		versionedEntryModelImpl._originalHeadId = versionedEntryModelImpl._headId;

		versionedEntryModelImpl._setOriginalHeadId = false;

		versionedEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VersionedEntry> toCacheModel() {
		VersionedEntryCacheModel versionedEntryCacheModel = new VersionedEntryCacheModel();

		versionedEntryCacheModel.mvccVersion = getMvccVersion();

		versionedEntryCacheModel.versionedEntryId = getVersionedEntryId();

		versionedEntryCacheModel.groupId = getGroupId();

		versionedEntryCacheModel.headId = getHeadId();

		versionedEntryCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = versionedEntryCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			versionedEntryCacheModel.defaultLanguageId = null;
		}

		return versionedEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{mvccVersion=");
		sb.append(getMvccVersion());
		sb.append(", versionedEntryId=");
		sb.append(getVersionedEntryId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", headId=");
		sb.append(getHeadId());
		sb.append(", defaultLanguageId=");
		sb.append(getDefaultLanguageId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.portal.tools.service.builder.test.model.VersionedEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>mvccVersion</column-name><column-value><![CDATA[");
		sb.append(getMvccVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versionedEntryId</column-name><column-value><![CDATA[");
		sb.append(getVersionedEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>headId</column-name><column-value><![CDATA[");
		sb.append(getHeadId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>defaultLanguageId</column-name><column-value><![CDATA[");
		sb.append(getDefaultLanguageId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VersionedEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VersionedEntry.class
		};
	private long _mvccVersion;
	private long _versionedEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _headId;
	private long _originalHeadId;
	private boolean _setOriginalHeadId;
	private String _defaultLanguageId;
	private long _columnBitmask;
	private VersionedEntry _escapedModel;
}