/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.dispatch.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DispatchTask service. Represents a row in the &quot;DispatchTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.dispatch.model.impl.DispatchTaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.dispatch.model.impl.DispatchTaskImpl</code>.
 * </p>
 *
 * @author Matija Petanjek
 * @see DispatchTask
 * @generated
 */
@ProviderType
public interface DispatchTaskModel
	extends AuditedModel, BaseModel<DispatchTask>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dispatch task model instance should use the {@link DispatchTask} interface instead.
	 */

	/**
	 * Returns the primary key of this dispatch task.
	 *
	 * @return the primary key of this dispatch task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dispatch task.
	 *
	 * @param primaryKey the primary key of this dispatch task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this dispatch task.
	 *
	 * @return the mvcc version of this dispatch task
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this dispatch task.
	 *
	 * @param mvccVersion the mvcc version of this dispatch task
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the dispatch task ID of this dispatch task.
	 *
	 * @return the dispatch task ID of this dispatch task
	 */
	public long getDispatchTaskId();

	/**
	 * Sets the dispatch task ID of this dispatch task.
	 *
	 * @param dispatchTaskId the dispatch task ID of this dispatch task
	 */
	public void setDispatchTaskId(long dispatchTaskId);

	/**
	 * Returns the company ID of this dispatch task.
	 *
	 * @return the company ID of this dispatch task
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dispatch task.
	 *
	 * @param companyId the company ID of this dispatch task
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dispatch task.
	 *
	 * @return the user ID of this dispatch task
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dispatch task.
	 *
	 * @param userId the user ID of this dispatch task
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dispatch task.
	 *
	 * @return the user uuid of this dispatch task
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dispatch task.
	 *
	 * @param userUuid the user uuid of this dispatch task
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dispatch task.
	 *
	 * @return the user name of this dispatch task
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dispatch task.
	 *
	 * @param userName the user name of this dispatch task
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dispatch task.
	 *
	 * @return the create date of this dispatch task
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dispatch task.
	 *
	 * @param createDate the create date of this dispatch task
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dispatch task.
	 *
	 * @return the modified date of this dispatch task
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dispatch task.
	 *
	 * @param modifiedDate the modified date of this dispatch task
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this dispatch task.
	 *
	 * @return the active of this dispatch task
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this dispatch task is active.
	 *
	 * @return <code>true</code> if this dispatch task is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this dispatch task is active.
	 *
	 * @param active the active of this dispatch task
	 */
	public void setActive(boolean active);

	/**
	 * Returns the name of this dispatch task.
	 *
	 * @return the name of this dispatch task
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dispatch task.
	 *
	 * @param name the name of this dispatch task
	 */
	public void setName(String name);

	/**
	 * Returns the system of this dispatch task.
	 *
	 * @return the system of this dispatch task
	 */
	public boolean getSystem();

	/**
	 * Returns <code>true</code> if this dispatch task is system.
	 *
	 * @return <code>true</code> if this dispatch task is system; <code>false</code> otherwise
	 */
	public boolean isSystem();

	/**
	 * Sets whether this dispatch task is system.
	 *
	 * @param system the system of this dispatch task
	 */
	public void setSystem(boolean system);

	/**
	 * Returns the type of this dispatch task.
	 *
	 * @return the type of this dispatch task
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this dispatch task.
	 *
	 * @param type the type of this dispatch task
	 */
	public void setType(String type);

	/**
	 * Returns the type settings of this dispatch task.
	 *
	 * @return the type settings of this dispatch task
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this dispatch task.
	 *
	 * @param typeSettings the type settings of this dispatch task
	 */
	public void setTypeSettings(String typeSettings);

}