/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HashAlgorithmEntry service. Represents a row in the &quot;HashAlgorithmEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.password.model.impl.HashAlgorithmEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.password.model.impl.HashAlgorithmEntryImpl</code>.
 * </p>
 *
 * @author arthurchan35
 * @see HashAlgorithmEntry
 * @generated
 */
@ProviderType
public interface HashAlgorithmEntryModel
	extends BaseModel<HashAlgorithmEntry>, MVCCModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hash algorithm entry model instance should use the {@link HashAlgorithmEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this hash algorithm entry.
	 *
	 * @return the primary key of this hash algorithm entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hash algorithm entry.
	 *
	 * @param primaryKey the primary key of this hash algorithm entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this hash algorithm entry.
	 *
	 * @return the mvcc version of this hash algorithm entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this hash algorithm entry.
	 *
	 * @param mvccVersion the mvcc version of this hash algorithm entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this hash algorithm entry.
	 *
	 * @return the uuid of this hash algorithm entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this hash algorithm entry.
	 *
	 * @param uuid the uuid of this hash algorithm entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this hash algorithm entry.
	 *
	 * @return the entry ID of this hash algorithm entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this hash algorithm entry.
	 *
	 * @param entryId the entry ID of this hash algorithm entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the create date of this hash algorithm entry.
	 *
	 * @return the create date of this hash algorithm entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this hash algorithm entry.
	 *
	 * @param createDate the create date of this hash algorithm entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this hash algorithm entry.
	 *
	 * @return the modified date of this hash algorithm entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hash algorithm entry.
	 *
	 * @param modifiedDate the modified date of this hash algorithm entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this hash algorithm entry.
	 *
	 * @return the name of this hash algorithm entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this hash algorithm entry.
	 *
	 * @param name the name of this hash algorithm entry
	 */
	public void setName(String name);

	/**
	 * Returns the meta of this hash algorithm entry.
	 *
	 * @return the meta of this hash algorithm entry
	 */
	@AutoEscape
	public String getMeta();

	/**
	 * Sets the meta of this hash algorithm entry.
	 *
	 * @param meta the meta of this hash algorithm entry
	 */
	public void setMeta(String meta);

}