/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PasswordEntry service. Represents a row in the &quot;PasswordEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.password.model.impl.PasswordEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.password.model.impl.PasswordEntryImpl</code>.
 * </p>
 *
 * @author arthurchan35
 * @see PasswordEntry
 * @generated
 */
@ProviderType
public interface PasswordEntryModel
	extends BaseModel<PasswordEntry>, MVCCModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a password entry model instance should use the {@link PasswordEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this password entry.
	 *
	 * @return the primary key of this password entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this password entry.
	 *
	 * @param primaryKey the primary key of this password entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this password entry.
	 *
	 * @return the mvcc version of this password entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this password entry.
	 *
	 * @param mvccVersion the mvcc version of this password entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this password entry.
	 *
	 * @return the uuid of this password entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this password entry.
	 *
	 * @param uuid the uuid of this password entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this password entry.
	 *
	 * @return the entry ID of this password entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this password entry.
	 *
	 * @param entryId the entry ID of this password entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the user ID of this password entry.
	 *
	 * @return the user ID of this password entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this password entry.
	 *
	 * @param userId the user ID of this password entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this password entry.
	 *
	 * @return the user uuid of this password entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this password entry.
	 *
	 * @param userUuid the user uuid of this password entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this password entry.
	 *
	 * @return the create date of this password entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this password entry.
	 *
	 * @param createDate the create date of this password entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this password entry.
	 *
	 * @return the modified date of this password entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this password entry.
	 *
	 * @param modifiedDate the modified date of this password entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hash of this password entry.
	 *
	 * @return the hash of this password entry
	 */
	@AutoEscape
	public String getHash();

	/**
	 * Sets the hash of this password entry.
	 *
	 * @param hash the hash of this password entry
	 */
	public void setHash(String hash);

}